
mort = []
mort.append(list("                                                                 `                    ``                                    `.oyhdmNmmmNmmNNmNNmdmNmdmmNmmNNmmNNNNNNNNNNNm"))
mort.append(list("                                                                                       .                  `----`    `-` .-` :osyddmmmmNmddmNmmNddNNNNNNNNNNNmmNNNNNNNNNNNN"))
mort.append(list("                                                                                     ` `.             `   .+ysy+:. `/o/:+ss+sddhddhddmmmdmmmmddmmNNNNNNNNNNNNNNNmmNNNNNNNN"))
mort.append(list("                                                                                      ` .`           `:-` .ydddshy.-dddhhhhddddhdhhmmmmmmNNmdmmNNNNNNNNNNNNNNNNNNNNNNNMNNN"))
mort.append(list("                                                                                      ```-          `:sy::-ydmmddd//dmmdhhdmmmmhhdhmNNmmNNmdmmNNNNNNNNNNNNNNNNmmNNNNNMMNNN"))
mort.append(list("                                                                    ` `               `..-.`.-``   `:shdhhhhdmmmmmddmmmdmdmNmmNmdddmNNNNNNdmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNm"))
mort.append(list("                                                                  `      `   ``       ```.-.+o:/.   /yhdddmddmmmmmNNmmmmmmmNNNNhddmmNNNmNmmmmNNNNNmmNNNNNNNNNNNNNmmNNNNNNm"))
mort.append(list("                                                                   ` ``` ```````    ``` `-oo/yys/` `oddmmddddmmmmmNmmNNNNNNNNNdyhdmmNNmmmmNNNNNNNmmNNNmNNNNNNNNNNNNNNMMNNN"))
mort.append(list("                                                               ``````..----....`````` `  .shhddhy/`.ydmmmmddmNNNNmmmmmNNNNMNmdhdmNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
mort.append(list("                                                       ```.....----:////+++++/--....```  `odhdmmhys+yhdmdddmmmmmddddmNNmNNNNmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNMM"))
mort.append(list("                                                    `.::///:::///:+//+//////////::-----...-+shmmmhhyyhddmmdmNmdmmmmmmNNmmNmmmmmmNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNmNNNN"))
mort.append(list("                                                  `-///+osyo::+o/:+++++++++++/+++//::-----...:+ydmdhhdddmmmNNmmmNNNNNmmmmmmmmdddmmNNNNNNNNNNNNNNNNNNNNNNNNNmmNmmNNmNNNNNNM"))
mort.append(list("                                                `-/+/:/+++y+/-++///+/+//::/++++++++o+/:::::-----/oyhhdddmmmNNNNNNNNNNNmmmNNNmdmNmNNNNNNNNNNNNmmmmmdmmmNNNNNNNNNNmNNNNmmmNN"))
mort.append(list("                                              `.::/::/++:++/+-/++:+//++/+///:://+++++o++///+/::::::oyhdmmmNNNNNNNNNNNNNmmNNNmmNNNNNNNNNNmmmmdddmmmmmmmNMNNNNNmNmNNNNNNNNNN"))
mort.append(list("                                            `.-/://:/+//-+::/:////+/:://///////::/++++ooso++++///////shmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmNmmmmmmmNmNNNNNNNNNNNNNmmNNNN"))
mort.append(list("                                          `..:////::+//::+:///:///+:://:////++++/::+o++oosysooo+o++++/oymmmNNNNNNNNmmNNNNNNNMNNNNNNNNNNNmNmNNmNNNNNNNNNNMNNNNNNNNNNNNNNNNM"))
mort.append(list("                                         `..://:+-:/o/::o:://+++//+//:///:////+sso+//+oo+osyhhysoosooo+osyddmNNNNNNNNNNNNNNNNNNNNNNNNMNNmmNNNNNNNNNNNNNNNNNNNNNMMMMNMMNNMM"))
mort.append(list("                                        `.-://:::::+++::s:/://s+o//o//:///:/+///osss+/+ssoosyhmdysssssssosydmNNNNNmdmmmmmNNNNNNMMNNNMMNddmNNNNmNNNNNNNNNNNNNNNNMMMMNNNNNMM"))
mort.append(list("..```                                  `--:/:::::::+/+/:s////:+s+o/oo///+////+++/+syhyo+oyysshhdmmhyyyyyyoydmmmmmmmmmmmmmmmmNNNNNNNNNdddmNNNNNNNNNNNNNNMNNNNNNNNMMNMMMMMNM"))
mort.append(list("::-.`                                 `.::::-+://:///++:oo++///osoo+oo///o++/++oo+/oshhsoshhhhhddmmmdhyyhysyhdmmdNmmmmmmNNNmNNNNNNNNdmmNNNNNNNNNNNNNNNNMNNNNNNNMMMMMMMMNNN"))
mort.append(list("--..`                                 .:///:/+:/+//+++o:/so++/o+ssoooss+++oso+++osoooyhhhyyhddhhmddmmmdyhhyyyhdmmmmmmNNNNNNNNMMNNmmmmNNNNNNNNNNNNNNNNNNNNNNNMMMMNMNNNNNNmm"))
mort.append(list("--..``                               `-/+::/+++:o+++++s/:sso++o++sysossso++oyysssssysoshhdhhhddddmmdmmmdhhhyyyddmmmmmNNNNNNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNMMNNNNNmmmmm"))
mort.append(list(".:::..``                            `-:/+/:o+/+:+soo++oo//ys+++oo+syssosooo+oshhyyhyyssyhhddddddddmNmmmmdhhhhhydmddmmmmmmNNNmmNNNNNmmNNmNNNNNNNNNNNNNNNNMMMMMMMMNNNNmdmmNN"))
mort.append(list("--::-::-`                           `-:/+/:o++//+soosoooo+oys+/osoossso+oossooshdhhddhyyyhhdmmmmmddmNmmmdhhhydhhdmNNNNNNNNNNNNmmmNMNNNNNMNNNNNNNNNNNNNMMNNNNNNNNNNNNmmmmmm"))
mort.append(list("--.-.-::-.`                         .-/+/::++o//+oysossoss+shyo++sssssso++osyysshdhhddddhhdhhmNNmmddmmmmmdhdhddhhmmmmNNNNNNmmmmmNNNNNNNNNNNNNNNNNMMMNNmmmmmmmmmdmNNmmmmddm"))
mort.append(list("/-..---:-:.``                       .-/++/:++s//+osyssyssysoyyyo+osssysso++osyhyshdddddmdhhddddmmNNmmddmdmddhhddhhmmmNNNNmmNNNNNNNNMMNNNNNNNNMMMMMNNNmmmmmmmmmmmNmmdddmmmm"))
mort.append(list("/:://::::/:-.`                     `.:/o+////so/+ssysyyyhyyysyhyossyssssssooosshhyyhdddmmmdhddddddmNNNmddddhhyhhhhyhmNNNNNNNNNNNNNNNMNMMNNNMNNNmmmmmNNNmmmmmmmmmmmmmmddddd"))
mort.append(list("//:::-....--.`                     `.-/+++/+/+so+ossysyhhyyhhhhhsooosyyyyyssyyyhhhhhhhddmmmmddddddhddmmmmddhhyyyyyyydmNNNMNNNMMMNNNMMMMMMNNmmmdmmmmmmmmddmmmdddddddmmmmddd"))
mort.append(list("///:...-::-.````                   `.-/+o/+++++sosoyyyysyhhhyhhhhyyssssyyhhyyyhhhhdddhyhdddmmmddddddhhhhdddhhyysosysdmmNNNMMMMMMNNNNMMMMmhddmmmmNmddmmmmNNmddddmddddmmmmdm"))
mort.append(list("::/::///::::-.````                 `.-/+oo+o++sooyyyyyyhysssyyyyyshhhhdhhhdddddddddddhhyyyhhddmddmdddhhhyyhhhhhys++osdmmmmNNNNNNNNNNNmmmddmmmddmNmmmmmmdddmmNNNmmNmdmmmmmm"))
mort.append(list(":///:/+//::.`````` `                .://os+ssysyyhhhhyyyhyyyssssysssyyyysoooosssssssyyyyyyyyyyhdmmmmmmdddhhhyyyyso++oymNNNNNNNNNmmdmmmmNmmmmmmmmdhhhddmmmNMNmmmmmNmNNmmmdd"))
mort.append(list("-///:://:--.```````                `.:+:oyssysyyyhhddhhddhyssoooo++/////+oossyyssooo+oooosyhdmNNNNNNNNmmmmmmddhdhso++ohdNNNNNNmmddmmmmmddddmNNddddddmNNNNmNmmNNNNmmmmmmmmm"))
mort.append(list("-:/++:/:.```.`.``````              `.-+++syysysyyyhddhsyddys+////////+osyyhddddhhyyso++++oshmNMNNNNNNmmmmNNNNNmdhhhmmmmNNMMNmmmNNMNmmmmmmmmNMmdddmmmmmdmMNmmmmmNmmmmddNNMM"))
mort.append(list(".-:-////.`-.``..````` `          ```.-/soosyyyyyyyyyhhyssyhyo/////++oyhmNNNNhhdddysso//://oymmmmmmddddddhdNMNNmdhshdmmNNMMMNmmdmNMmmmddhhhhdmdmmmdhyyyydNmmdddmmmmmmmmmNNN"))
mort.append(list(":-.-//::-``````.````````  ` ``````...-/sssyyyyhhssyyhhhhhhyyso+//++oosssssyyyyyyys++/::--:/+ydmmdddhhyyyyydNNmdhhsoosydmmddmddmNNNmdmmmmddmmmdmmdhhhddmmmmmNNNmmdmmdmmNNNN"))
mort.append(list("/:-.-///:-.````-..--..```````...-----:/sshdhyhhhhyyyhhhhdmdhyyo//::-::://++osssso+/:::-----:+syyyyysssoooosNNmdhso+oooshddmdmmNNmdmNMMNmmdhhhhdddmmmmmmmddmmddddddmNNNmdhh"))
mort.append(list("-///+//+:::....-:::::----......-----//+osdmmhhddhddhdddmmmmdhs+/:------::://///::-----.....-:+sssoo++/////+dNmdyso++oydNNNNNmmmddmmmNmddddmNNNNNNNmmmddddddhhdmmNNNNmdhdmm"))
mort.append(list("-://///+:::-----::///:::---...-----://+osddddhhdhdNmdmmmmmmddy+/:----.-.---------------.....-:+oooo+////://ymdhyyyssydddmmmdmdddmmmNNddmmmNNNmdddmhhddddhdddmmmddddmNMNmmd"))
mort.append(list(".----:://::/:::::://///:::---------:://osdmmdhddhhdmNNNNmmhhdho/:--..........---:--------.....-:+oo++/////+smdyyyhddmmmddmmmmmdmNmmmmdmmNNNmdddmmdhyhmNNNNdhhhhhhmNMNNmmhh"))
mort.append(list("-.----::+///////////////::-------::::://ohmmmdddmdmmmNNNNddhhhs+:--.........--:::::/:----......-:/+o+++++ooyhhhyyhhddhhhmmmNNNmmdddddddddNmmmmmmmmmmmmmddmmhdmmmNmmmmNNNmm"))
mort.append(list("-----:::/+/////:::+///////:::::::::::///+ydmNmddmmmmmmNNmmddhyo+/:---....----::////+:-.----.-:///oosssoossyyyhhhyhdmNNmNNNdhddddhddddmmmNNmdddddddddmmNNNNNmmdddhhhhdmNmmm"))
mort.append(list("---:::://++++///+++++////::::::::://++/+osydmmmmdmmmmmmmmmmddhs+//:-------:::://+//+///+oooo+oyyhsoosssssyhysyyhdNmmddmmdmmmmmmmmNNNMNNmmdhhhhhdhhdNNNNmdyhddddddddmmNMNNN"))
mort.append(list("--::::///++++++oooo++/////::::://+++ooooshhyddmNNNmmmmdmdddhyys++/:::::::::///++/::::/+osssyhhhhso++ooooshdhyyhhdmdhddmmNddmmmmddmmmNNNmmmdmmmmmNNNmmmdddyhdmmmmmNNmmmmddm"))
mort.append(list("::::::////+ooo++oooo+++/////+++oooossssyyhdyshmNNNNmmmmmdhyyso+///::::://///+++/::::-:://+oyyssooooyso++smmdhyyhddddddmNNddddmmmmddddmNdhhhhddddNdddmmdmNmmmNNNNNmmddmmmNm"))
mort.append(list(":-::::///++oooo+sssoo+++++oossssyyyyyshmmmmyyhmmNNNNmmmmdhso++///://///::////:::::::-:://+oosssyhdhso++ohNmdhhdhdddddddmmdddmmmmmmmmmNNddhhhhddmMNmNNNNNmmmmmmmmmmmddmmdmm"))
mort.append(list("o/:::://///+ooo+syyso+ooossssyyyyyyyyhdNNmdyydmmNNNNmmmdNhyo+//::::///::::::///oysssssyyyyhhhddhhhso++oyNNNmdhdmhdhhhhdhmdddmmmmNNNNNNMmddhdmmmNmmmmmmmdmmmmmmmmmmdddddddd"))
mort.append(list("ho/////////+oooooyhysoosyyyyyhhhyhhyyhhmmmdhdmmmmNNNNmmmNmhy+//:::::/:::::::://+//+++oooossssssyyysoooymMMMNmddNmddddhmmhmddddmmmmmdmmddhddmmdmmmmddmdddddddddddhhhhhdhhhh"))
mort.append(list("dy//////////+so+oshysssyyyyhhhhhdddhdddmmmmmmmmdmNNNNmmNNMhsso///::://::::::///:::::///++oossyyhhysosymMMMMNNmmmmmmmmdmNdmmhdmdmddmdddmmmmmdddddddddddhhhhhhhhhhhhhhhhhhhh"))
mort.append(list("dh+///////++/os+++oooosyhhhhhhdddddmddddmNNNmNmNNNNNNNNNMMNsoo+//:///::::::://:::::///++osyyhhhysoooymMMMMMNNNNNmmmNNNNNddmdhdNdddddddddddhhhhhhhhhhhhyyhyyyhhhhhhhyhhhyyy"))
mort.append(list("dds///////+++///::/syssyyhddddddmmmmmmddmNMMNNMMNNNNNNmNMNNmo+oo+/////:/:::::::::::::////++oso++//+smMMMMMNNNmmNmmmmmMNMmmmdhdNmdddhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyysssss"))
mort.append(list("ddy+///:----:/+o+/////+oyhdhhhddddmmmmmmmNNMNmMMMMNNNmmNNNMNh++syyso++///::::::::--------:://////+omMMMMMNNNNmmmmmNmmNNNmmmdddNmmhmdhyyyyyyyyyyyyyyyyyyysssssssoooosooooos"))
mort.append(list("ddy+:-..``.-//:::////+osyyyyhhhyyhmmmNmmmmNNMNNMMMNNmmmNNNMMNo/+oosyys+o+++/:::::-------::/+++/+osmMMMMMMNNNNNNmmmmmmNNNNmmmdmNdmddNdhysyyyyysssssssssssssssoooooooooooooo"))
mort.append(list("o+++-....`--:///++o+osooo+ossyyo++dmNNNmmmmNMMNNNMMMmmdNNNNMMms+//::----:/+o/::+++/::::://++++oyhNMMMMMMMMNNNNNNmmmmmmddmmmmmNNdNddmmhdyssosoooooooooooooooooooo+ooooooooo"))
mort.append(list("hhs+:-:::-:::/ssyyssooo+oooshhdhssdmNNNNmmmNNMMNNNMMMmdmNNNNNNNh/.........------:/oo+//++oso+++++sMMMMMMMMMMNNNNNmmmdmmddmmmNNmmNdmmdddmsooooo++++oo+ooo+ooo+o+++++ooo++++"))
mort.append(list("++////:------ohhhhdhhmdhdmyhhhmhysymNNNNmmNNMMMMNNMMMMmmmmmNNNNd..````````....````......-::-....-/mMMMMMMMMMMMNNNmmmmdmmdhdmNNmNNdNNdmhNmoo+++++++o++++++++++++o++++o++oo+"))
mort.append(list("/:---------::+syhhhysyssyyssysssssydNNNNNMMmMMMMNNNMMMMNNmmmmNms``````````...`````````````.`...-+ymMMMMMMMMMMMMNNNNmmmmmmmdhmmNNmmNNmdmmNmo++++++++++++++++++++++++++o++++"))
mort.append(list("---------:::////+////////////+syshddmNNNNMMmNMMMMNNNNNNNMMNNNMNh---......---...````..`````...--:hdNMMMMMMMMMMMMMMNNmmmmmmmmmmNNNmNNdmhmmNNmo++++++++++++++++++++++++++++++"))
mort.append(list("---------:::::::::::-:---::/oyhshddmNNNNNMMmNNMMMMNNmNNNNMMMMMMMh/:-------::::--------....--:::/omMMMMMMMMMMMMMMMMNmmmmmmddmNNNNNNmNddmmNNNNs+++++/+++++++++++++++++++++++"))
mort.append(list("..........------.------:oyhhdmdsmdmmNNNNMMMNNNNNMMMNNmNNNNMMMMMMMy:::---:::::::::::::::-:::://///NMMMMMMMMMMMMMMMMMNNNNNNmdNMNNNmmNdmmmNNNNNNds+///+//++/+++++++++++++++++"))
mort.append(list(".....--............---+hhhhhyhmymmmmNNmNNNNMNNNMMMMNNmNNNNNMMMMMMMo:------:::::::::::::::::/++++ohMMMMMMMMMMMMMMMMMNNNNNNmmNNNmmNmmNNmmmmNNNmmmhy++////++++++++++++++++++/"))
mort.append(list("-.............------+hddhhhhhhdhmmmmmdNMmddddNMMMMMMNNNNNNNNMMMMMMNy/::-----::::::::-:::::/+++++++NMMMMMMMMMMMNNNNNNNMMMMMNNNmdmmmmmmmmddmmNdmmmNmy++///+++++++++/++++++++"))
mort.append(list(".........------:::+yhhhhhyyhdddddmmmhNMmNmNNNMMMMMMMNNmmNNNNMMMMMMMMms/:::::::::::::::://///++++++hMMMMMMMMMNNNMMMMMNNNNNmdyhmdddmmmNmmddddmmmmNNNmmyo++/++//+++++++//++++"))
mort.append(list("----------------/yddhhhmmmddmmmmmNmmNMNmmNNNMMMMMMMMMNNNNNmmNMMMMMMMMMms/::::::::::::///////////++sMMMMMMNNMMMMMNNNNmmmmmsho/mddddddmmdddmmmmmmmNNmmNmh++////+++++++++++++"))
mort.append(list("---------------odhhhdhyydmmNmdmmNNNNMNmNNdmNMMMMMMMNMNNmmdmmNNMMMMMMMMMMd+::::://://///////////++oomMMMMMMMMMMNNNNNNNNmmmhyymmmmNNmmmmmmmmmdmmdmmNmNNho+++/+++/+++++++oooo"))
mort.append(list("-------------:ydhhyyyhshyyydmmNmmmNNMNNNmmmhNNMMMMMMMNmmddmmmmNMMMMMMMMMMNs/:::://////+++++++/++oosdMMMMMNNNNNNNNNNNNNNNNmmmmNNNmmmmmmmNNNNNmmdmmmNNNdo++++++++++oo+++oo+o"))
mort.append(list("-------------ydhhhyysysyyyyhhhdmNmNNNNNNmmdmNNNMMMNNNNNmmmmmNNNNMMMMMMMMMMMh/:::////++++++++++oosyydMMMMMNNNNNNNNmmmmmmmNNNMMMNNmNNNNNNNNmmmNmmmmNNNNmmyo+//+/+++/+o+/++++"))
mort.append(list(".........-.-odddhyyyyyhhdddmmdhddmmmNNNNNNNNNMMNNNNNNNNNNmmmmmmmNMMMMMMMMMMMy::::://++++//+++osyyhhmMMMMMNNNmmmmmmmNNNMMMMMMMMMNNmmNNmmmmmdddNNNNdNNmdddms++++++++++//++++"))
mort.append(list(".........--+ddhhhhhhhyhhhdmmmNNNmmmmNMNNNMMMMMMMMMMMMMMNNNmmmmNNNNMMMMMMMMMMN/--:://////:////+osyyhNMMMMMNNmmNNMMMMMMMMMMMMMMMMNNNmmNddmddmmmNNmddNNmddhdNh+++++++++++++++"))
mort.append(list(".....-----/dmddddhhhhhhhhhhdddmNNNNNmNNNNMMMMMMMMMMMMMMMMNNmmmNmmmNNMMMMMMMMM+---::::::-:::://+osydMMMMMMMMNMMMMMMMMMMMMMMMMMMMMNNmmNmmNmNNNMNmddmmNmmdhhmNdooo++++oooo+oo"))
mort.append(list("---------:dNNdhdmmdhhddddddddmdmmmNNNNNNNNMMMMMMMMMMMMMMMMNNNmmmNNNNMMMMMMMMM/..---------::://+oshNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmNNNNMMMMMNdmmmmMNmdhhdNNmsoo++ooooo+++"))
mort.append(list("-:-:::-::oNNNNNdhdmNmhhhdmmdmdddmmmmNNNNNNMMMMMMMMMMMMMMMMMNmNNNNMMMMMMMMMMMMo-...-......----:/oymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMNMMMMMMMNmdmmMNmhhhdNNNNyoooooooooos"))



ninja = []
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmshy////////+yssssshddmmmdmNmNNNNNNNNNNNNNNNNNNmmNNNNNNNNNmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMmNMNNNMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNsyd////////+hsssssymmmmdmmmNNNNNNNNNNNNNNNmdhhhhhhhhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNMMMMMMmNNNNMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMysm/////////ysssssymmmmmmmNNNNNNNNNNNmddhhhhhhhhhhhhhhhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMNNNNNMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsm/////////ysssssymNmdmNNNNNNNNNmddhhhhhhhhhhhhhhddhhhNMMMMNNMMMMMMMNNNmdhyooyyyyyhmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMNNMNNMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsm+////////syssssymmmmNNNNNNNmdhhhhhhhhhhhhhhhdddddddmMMMMNNMMMMMMNNNNmmdyo/oo+/-`.:ohdNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmsds////////oysssssddmNNNNNmdhhdddhhhhhhhhhhhhddddddhNNNNNMMMMMMMMMMMMMMNNmdddhys+:+oshdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNshh////////oyssssshmNNNNNddhhhhhhhhhhhhhhhhhdhhdhhhNmNMNNMMMMMMMMMMMMMMMMMMMMMNmhdh++dmdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMNNNNMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyyd////////+yssssshmNNNmdddhhhhhhhhhhhhhhhhhhhhhhhdMdMNNNMMMMMMMMMMMMMMMMMMMMMNmmmh:/hmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMysm/////////yssssshNNNmdddmddhhhhhhhhhhhhhhhhhhhhhmmNMmNMMMMMMMMMMMMMMMMMMMMMMNmNmh:smNNMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsm+////////ysssssyNNmddmmmdddhhhhhhhhhhhhhhhhhhhhNdMMmNMMMMMMMMMMMMMMMMMMMMMMNmNmy/dNNMMMMMMMMMMMMMMMMMMMMMMMMNmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsdo////////yyssssyNNNNmNNNNmdhhhhhhhhhhhddhhhhhhdNmMMNMMMMMMMMMMMMMMMMMMNMNNNmhyh++dmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMNMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmshs////////syssssymNNNNNNNNmdhhhhhhhhhdddddhhhhhmmNMMMMMMMMMMMMMMMMMMMMMmMMMNm/s+ ohmdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNsyh////////oysssssmNNNNNNmmdhddhhhhhhdmNmdhhhhddNmMMNMMMMMMMMMMMMMMMMMMNNMMNNd:s:`sdmdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmNMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMysd////////+ysssssdNNmmdhhhhddddddhhhdNNmdddddddNNMMNMMMMMMMMMMMMMMMMMMNNMMNNd/y..ymmdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsm////////+hssssshhhhyyhdhhdddddddhdmmmdmdddddmmNMNMMMMMMMMMMMMMMMMMMMNMMNNNy+o`/hddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsm+////////ysssssyhyyhhhhhhhhhhhhhhddddddmmmmmNmMMNMMMMMMMMMMMMMMMMMMMNMMNNm+s+`odmdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmsdo////////ysssssydhhhhhhmmhhdhhddddddddmNNNmmNmMMNMMMMMMMMMMMMMMMMMMMNMMNNm/y:`sdmdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNshy////////yyssssydhhdhhhhddddhhdddddddddNMmddmNMNNMMMMMMMMMNMMMMMMMMNMMMNNh+y.-yddNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMsyh////////syssssydhhhddhhhhhhhhhdddmNmmmNMNNNmms+yhdmddmMMMNNMMMMMMMMMMMNmdhy.ohdymNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMysd////////oyssssymmdhhhhhhhhhhhhddddNMMMMMMMMMds:/oydoodMMMmdMMMMMMMMMMNNddds.yhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsm////////+yssssymNmdhhhhhhhhhhdddddmmmmmNmNNNNNNNNNMMMMMMMMMMMMMMMMMMMNNmyy::odmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsd+///////+hssssymNmmdhhhhhdhdddddddddddmmmmdNMMMMMMMMMMMMMMMMMMMMMMMMMNmdh+./ydNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmsdo////////ysssssdMNmmdddhhdddhhhhhmmdmmmmNNNMMMMMMMMMMMNNMMMMMMNNmmNNNmhsys-hddmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNshy////////yssssshNMNNmmddddddhhddddmmNNNNNMMMMMMMMMMMmmmNmmhhdmmhyydmmdh+yssdNNmNNMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyyh////////yysssshNNMNNNmddmdddddddmNMMMMMMMMMMMMMMMMMNdmmNNy+shdhyhhhhhhdhyyyhhddmmmNNMMMMMMMMMMMMMMMMMMMMMMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNMMMMMMMMMMMMMMMMMMMNmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMysd////////syssssyNNMMNNNmmmNmmmdmmmNNNNMMMMMMMMMMMMMMNmdmmmdhdmhyyyyyyyyyyysssssssssyyhddmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMMMNMMMMMMMMMNmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsm////////oyssssyNNNNNNNNNmmNNmmNNNNNNNNNNMMMMMMMMMMMMmdddhhdddsosyyyysssssssssooooossyyhhhddmhydddmNMMNMMMMMMMMMMMMMMMMMMMMMMMNMNMMMMMMMMMMMMMNNNNMMMNNMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsd+///////+yssssyhhhhdmmNNmmmNNNNNNNNNNMNMMMMMMMMMMMMMmdddhdddyoossyyysooosssssooossssyyhhddddysssydNNMMMMMMMMMMMMMMMMMMMMMMMNNMNMMMMMMMMMMMMMMMMMMMMMMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMNN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmsdo///////+hssssyyyhhhhhdmNNNNNNMNNNNNNMMMMMMMMmNNNMMMmdddhhhhsoossssyhyssosssooooossssyyhddmhsyhmNMMMMMMMMMMMMMMMMMMMMMMMMNNNMMNMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNshy////////hssssyhhhhhhhhhdmNNMMNNNNNNMMMMMMMNddddmNmNNmddhhhdyssyhhyyyhsoooooooooossssyyhddmysydNNMMMMMMMMMMMMMNNNMMMMMMMNNMMMMNMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyyh////////yysssyyhhhhhhdddmmmNNNNNNMMMMMMMMNdddddmmmmNmddhyydmdhyysyyyoo++++++++ooosssyyhdddysyhmNMMMMMMMMMMMMMMMMNNNMMMMNMMMMMNMMMMNMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsd////////yyssyyyhhhddddmmmmmNNMMMMMMMMMMMNmddddhhddmNNmdhhhdmdhhyssoooo++++++++oooossyyhhmhyyyhdNNMMMMMMMMMMMMMMMMMMNMMMNMMMMMMNMMMNMMMMMMMMMNMMMMMMMMNNMMMMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsd////////syyyyyyhhhhddddmmmmmmNNNNNNMMNNNmddddhhddmNMMmdddhdmhhhyyssssooo+++ooooooossyyyhdyyyyhdmdyhdNMMMMMMMMMMMMMMMNNMNMMMMMMMMMMMNMMMMMMMMNMMMMMMMMMMMMMMNNNNMMNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmsd+///////oyyyyyyhhhhhhhhhhhhhhhhhhhhddhhhhhhhhhhddmNNMNmdyydddhhhyyssssssso+ooooooossyyhhdyyyyhhdmhyyyymmNMMMMMMMMMMMMMNNMMMMMMMMMMMmMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNsdo///////ohyyyyyhhddddddddddddhhhhhhhhhhddhhddhhhdhdmNMNhsshhhhhyssoooooooooooossssssyyhdhyyyyyhdmNNNmdsoosyhyyydmmmNNNmNNNMMMMMMMMMNMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyhy///////+hyyyyyhddddddddddhhhhhhhhddhhdddddddddddhdmNMNdhyhhhyyssso+o+oosssoosssssyyyhdhyyyyyyhhdmNNNNh+//:-/://///+++++++syyhdmNNNNMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyyh/////-//+syyyyhddddddddhhhhhhhhdddddddddddddddddddddmmmdddhhyysssoooosssoososssssyhhdyyyssyyyhhhdmmmmy/::--:----::::::/::://///+++osyhNMMMMMMMMMMMMMMMMMMMNMMMMMMMMNMMMMMMNNMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsd/////oyosyyyyyhddddddhhhhhhhhhhhhhdhhdddddhhyysssysssodmmmdhysoosssoooooooosssyyhhdhysssssyyyyhhddddmh+::--::-:::--------::::////////++shNMMMMMMMMMMMMMMMNMMMMMMMMMNNMMMMMMMMNNNMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsd/////yhsyyyyyyhdhhhhhhhhhhhhhhhhhhhhhhhyso+++++oooo+++ommmddhysooossoooosossyyhdhhyyssssssssyyyhdddhdh/::--:-------:::::::::::::::://///++shmMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMNNNMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmsd+////oyssyyyyyyhhhhhhhhhhhhhhdhhhhhso++++////+oo+++++//+mmmddhyssyssssssyyyhdhyyyyyyyyyssssyyyyhhdhhhy/::--:---:-----::::-::---::::::::///+++hMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMNNNmmNNNNNNMNNNmm"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNsdo///++-ymhyyyyyhhdddhdmddhhddddddy/:///++//////++///////+mmdddhyyyyyyyhhdddhyysyyyyyyyyssssyyyyyhhhhhh/:/:---:::/://+:://:yo+/:-:s/:o+::::/++ohMMMMMMNMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMNNmmNNNmmmmmN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyhy///os-omdyyyyhddddddddddddmddds+:-://///::::////////////+hNmmddmmmmNmmmhyssyyyyyyyyyyyssssyyyyyhhyhhs/::/-----.--:+hos--/s/+y://+ys+:::/:/+//+yNNNNNMNNMNNNNNNNMMMMMMMMMMMMMMMMMMNNMMMMNNMMMNMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyyh///+s-:mNdhyyydmmdddddmmmmmds/:/:://///::/://///////:::::/ohdmdNNmmddddddhyyyyyyyyyyyyssssyyyyyhyyyy+/:+:----..---:/oysshys//+ohy+::--::///+:+oyMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMmMMMNMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsd+///+:-/mdhyyyddmmmmmmmNmdo/:::/:///://::::::/:::::::::::://+/osmmdhhhhddddhhyyyyyyyyyssyyyyyyyyyyhho/-/-.--.-::::/:/yo++y/:/+yyss++o+//:::+::+ohMMMMNMMMMMMMMMMMMNMMMMMMMMMMMMmMMMMMMMMMNNMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsd++//+/.-hdhyyymmmmmmNmmds//:::-///:::::::::::::::::::::::://+//ohdmddhhhhhhhhhhyyyyyyyyyyyyyyyyyyhhs//:-..---://:::/o+syso+sssoydmdy/::/:::/-:/+omMMMNmNMMMMMMMMMNMMMMMMMMMMMMNmMMMMMMMMMMNMNNmdd"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmsd++//++.-+hyyyydmmmNNNmy+/:::::::/:-//:::::::::::/::::::::://///+oyhdddhhhhhhhhhhhhyyyyyyyyyyyyyyyhs/+:+.--:////+::oo/+ohdy+ohs++y+/:+:::--//-::/oommNMMmNMNNMMMMMmMMMMMMMMMMMMNNMMMMMMMMMmmdddddd"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNsho++/+o//+yyyyydNNNNmh+/:/:::::::/::/++//:::::::://:::::::/+o/://+syyhhhhhhhhhhhhhhhhhyyyyyyysssyyo/+/:---:/+o///:/o++osdyyyyo+++/:::/:----/:--::/osNMMMmMMMMNMMMNNMMMMMMMMMMMMMMMMMMMMMNhhhdddddd"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyyy++++o+ooyyyyyhdddy+//:////:::://-:++ooo//+/::::::::::::/+oso/:/++yyyyhhhhyyyhhhhhhhhhyyyyyyysys+/+:/---:+o+o+/o/ssssyshhhyyhs++/::/+/:::-/:--:::+oyMMNNMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMmhhyhhhdd"))
ninja.append(list("MMMMMMMNMMMMMMMMNMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsh++++s+ooso+oosyyo//:///::/:::///:://+ooo//+////////+o+oossss+:://ohhyyyyhhyyyyyyyyyhhyyyyyysso/////:-::/sss++/++yhdssyydysy++++///+/:::::/---:::/+odNNMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhhhhh"))
ninja.append(list("MMMMNNNNNNNMMMMNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsh++oos++oo++/++++++/:///:-:/::////-:///+oo/+//+++oooooosssssso:::/+syhyssyyyyssssssyyhyyyssoo+++/:/--::oosssyyhhhhhhhhydyhys+oo++/++/--:::/:-::--//+sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhhhh"))
ninja.append(list("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMdsyoooos+/++oos+///+oo/:://--//:///+::://++oo++///++oo+oosssssss+///oooshhysssyssoooooshyss+:::o+/o:-:::ydyyhhhhhhhhhhhhhhyhhsyssso++o/--:://::::--///ohMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhyhhh"))
ninja.append(list("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMNNmyoo++++++//+++oss//+ooy+:::/:-://///+/::/+++ooo+////++++ooossyssso+//+oo+osyhyssssooooosyss/:/+::+oso/:/oyhhhhysyyhhhhhhhhhhhhyyyhysy++:--::+/:-:---://+omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhyhhh"))
ninja.append(list("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMNNNMMMMMNNhsoo+++++++++++++os/+osh+::-::-:://///+/://+++ooo////+++ooossyyssyso++++oo++oosyyyysssssyhs/:+//:++/oysssssyhhs/so:ohhhhhhhhhhhhdmmmdhhs/:-:/+::::---/////sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhyhh"))
ninja.append(list("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNMMMMMMMmyssssssoooo++o++ydo+osh/::::::--:////++:////+oossooo++++ooossyssysoooso+oso+ooosssyyyyyyo///+++syysdssssssyhho+syoohhhhhhhhhhhdmNNNNNNNNmhss+:::---:///+//mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhhyhh"))
ninja.append(list("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMNyoo+oooossssssssyhdhysyh/:::::::-:////+o/////+oooooo+ooooo+oosyssyyssssssoo//////+++++o+::/shddmmmyhyssyhysyhhyo+oshhhhhhhhhhhhhmNNNNNNNNMMMNNds+:--:/:/+:/sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhhyhd"))
ninja.append(list("NNNNNNNNNNNNNNNNNNmNNNmNNNNNNNNNNNNNNNNNNNNMMMMMMMMmyo++++++++++++oooooyyyyhh+::://///:////+o+////+oossoso++++ooo+++ossssoooossso+/+///+++++oyhmNNNNNNmmhyyh+mhssyhhhhhhhhhhhhhhhhhhdmNNMMNNNMNMMMMMMNNds+::/+::/yNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhydd"))
ninja.append(list("NNNNNNNNmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNmmmmmMMMMMMMMmysssoooooooooooosssys+ooo+://///+++/:://+o+///++osoosys++++o+/++o+oooo+o+oosso++/:///oymNNNNNNNNNddyyydmddsysyyyhhhhhhhhhhhhhhddmNNNNNNNNNMNMMMMMMMMMNh+//:://hmmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhdd"))
ninja.append(list("mmmmmmmmmmmmmNNNNNNNNMMNNNNNNNNNmmmmmmmmmmmNMNMMMNNmNmhyssssssssssssssyss/////////////++////+oo+/+++ooooosyso+++//+++o+++++////ooo+++//odNMMMNNNNNNNmhhyyhNmyyysssyyyyhhhhhdhddddmmNNNNNNNNNNMMMMMMMMMMMMMMNdo://:oNmmmmmmNNMMMMMMMMMMMMMMMMMMMMMMMMhhhddd"))
ninja.append(list("mmmmmmmmmmmmNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmNMNmmddmmmNho+++++++++oooooosso////////////++o+//++oo++++ooo++oosssoo++ooosso++////++++++oymNMMMNNNNNNNNNddhhyyhyyyyyyssyyyyhhhhhhhdhdmNNNNNNNNMNNNMMMMMMMMMMMMMMMNs/ohmNmmmmmmmmmmNNMMMMMMMMMMMMMMMMMMMmhhhdmm"))
ninja.append(list("mmmNNNmmmmmmmmmmNNmNmmmmmmmmmmmmmmmmddmmmdmNmdddddmmmmmyoooossssssyyyyyhds:///+//////++++++/++oo+////+o+/oossssssssssssoo+/////+//+ymMMMMMMNNNNNNNNdhdyhmyyyyyyyysyysyyyyyyyyyyyhNNNNNMMMMMNMMMMMMMMMMMMMMMMMMMhMNdsohdmmmmmmmmmmmNNMMMMMMMMMMMMMMmhhhdmmm"))
ninja.append(list("mmmmmNmmmmmmmmmmmmmmmmmmmmmmmdddddddddmmmmmdddddddmmmmmNmdhyysssssossssyds++++++++++///++++o++ooo+///+++/oosyyyyyyyyyyssoo++++++/odNMMMMMMMMNNNNNNmhhhddyssyyyyyyyssysyyyyyyyyyydNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMNs+///+sddddmmmmmmmmmmNNNMMMMMMMMNdhhhmmNNN"))
ninja.append(list("NmNNNNmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmmmmmmdmmmmmmmddmmysooosssyyhhhmdoooosoo++++++++++osooooso+///+////+oosyysosssssooo++///yNNMMMMMNNMNNNNNNNNdhdhyyyyyyysyysyssyyyyyyyyyyhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/-:::/+hmddddddmmmmmmNNNNNNMNNmdhhhdmNNNMM"))
ninja.append(list("NmNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmmmmmddmmmddddmmdhhddddmmmNNmhoooossyyyyyhhhhyyssshysss++////////+++oosoooooosso//++hMNMMMNMNNMNNNNNNNNNNNmdhhyyyyyyyyyyyyyyysssyyydNMMMMMMMMMMMMMNNNNNNMMMMMMMMMMMMN:--:::/hNNNmmddddddmmmmNmmmmdhhhhdNNMMMMMM"))
ninja.append(list("NNmmNNmmmmmmmmmmmmmmmmmmmmmmmmddmmmmmmmmmmNmmmmmmmmmmmmdmmNNNNMMMNNNNdysoossyyhhdNNNNMMMMNNNNMmdhho++////////++ooossssooooo+++yNMNMNNNNNNNNNNNNNNNNNMMNNmmdddhhhhyyyyyssssssydNMMMMMMMMMMNNNNNNNNNNNNNMMMMMMMMMd:---:odNMNNNNNNmmdddhhhhhhhhddmNNMMMMMMMMM"))
ninja.append(list("NNmmmmmmmmmmmmmmmdmmdmmmmddmddddddmmmmmmmNNNmmmmmmmmmmmmmmNNNNNmmNNNmmdmmmNNNMMMMMMMMMMMMMMMMMMMNNdo++/////////+++oosoossssssymMMNMNNNNNNNNNNNNNNNNNNNMMMNdhhhhhhhhhyysyssssydMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMMMN+-:+ymMMMMMMMNNNNNNNNNNNNNNNNNMMMMMMMMMMMMM"))
ninja.append(list("mmmmmmmmmmmmmmmdddddddddmddmddddddddddmmmNNNNNNmmmmmmmmmmmNNNNNdddNmmNmMMMMMMMMMMNNNNNNNNNNNNNNMMMMdo++////////+++ossssssooossNMMMMMNNNNNNNNNNNNNNNNNNNMNdhhhhhhhhhdmdyyyyyydNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMmyoydNMMMMMMMMMMMMMNNNNNMMMMMMMMMMMMMMMMMNNNN"))
ninja.append(list("mmmmmmmmmmmmmdmddddddddddddmddddddddddddmNNNNmmmmmmmmmmmmNNNNNNddmNmNMMMNNNNNNNNNNNNNNNNNNNNNNNNNNMMdo+++///+////+++ooosssssssmMMMMMMNNNNNNNNNNNNNNNNNNNMmdhhhhhhhhmMNmdhhdNNNmNNNNNNNNNNNNNNNNNNMMMMMMMMMMMNmmmmmNMMMMMMMMMMMNNNNNNNNNNMMMMMMMMMMMMMMNNNN"))
ninja.append(list("mmmmmmmmmmmmmdmddddddddddddmddddddddddddmNNNNmmmmmmmmmmmmmmNNNNmmNNmmNMMNNmNNNNNNNNNNNNNNNNNNNNNNNNNMhso+++//////+++++oossssssmMMMMMMMMNNNNNNNNNNNNNNNNNNMNNmddddmmNNNNddmmdhhddmmmmmmmNNNNNNNNMMMMMMMMMMMMMNmddmmNMMMMMMMMMMMMMMMNNNNNNNNMMMMMMMMMMMMMMNM"))
ninja.append(list("mmmmmmmmmmmmmmddddddddddmdddddddddddhddddNNNNNmmmmmmmmmmNNNNNNNNNmdmmmMMMNmmmNNNNNNNNNNNNNNNNNNNNNNNNNdo++//+++++///+++oooossshNMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNmmmdhhysyoosyyhhddmmmmmmNNNNNMMMMMMMMMMMMNNddddmmNNNNNMMMMMMMMMMMMMNNNNNNNMMMMMMMMMMMMMMM"))
ninja.append(list("mmmmmmmmmmmmmmmmmmddmdddddddddddddddhhdddmNNNNmmmmmmmmNNNNNNNNNmyssdmmNMMNNmmmmNNNNNNmmmmmmmNNNNNNNNNNMds+++++///++++++++++oosymNMMMMMMMMMMMMNNNNNNNNNNNNmmdhhddddddhyyyosso+osssssyyhddmNNNNNNNNNMMMMMMMNdhhhhddmmNNNNNNNMMMMMMMMMMMMMNNNNNNNNNNNNMMMMMMM"))
ninja.append(list("mmmmmmmmmmmmmmmmmmmdddddddddddddddddhhhhhdmNNNNNNNNNNNNNNmmmmhsoooohmNNNNNmmmmmmmmNNNNNmmmmmmmNNNNNNNNNMds++////++++//+++oo++oosdMMMMMMMMMMMMMMMMMNNNNNmmmmddddddhhyssso///:-.-::-/oyhdmmmmmNNNNNNNNNNNNmhhyyyhhddmNNNNNNNNNNNMMMMMMMMMMNNNNNNNNNNNNNNMMMM"))
ninja.append(list("mmdmmmmmmmmmmmmmmddddddddddddddddddhhhhhhhdmmmmmmmmmmmmmmmmmmsoooooyNNNNNNNmmmmmmmmmNNNNmmmmmmmmNmNmNmNNNmso+++////////++ooo+oooshNMMMMMMMMMMMMMMMMMMMMMMMNNNNmmdhyo+/-`  `.::/+o+osssyyhdmmmNNMMMNmddhhhhddhhhhhhdmNNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNNNNNNN"))
ninja.append(list("mdddmmmmmmdmmmmmmmdddddddddddddddddhhhhdhhhdddddddmmmNNmmddddyooooosdNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNyo+/////////++++++oooooydNMMMMMMMMMMMMMMMMMMMMMMNNNNmmdhso/:.` `.---::-.:+sydmNNMMMMNNNNmddhhhhhhhhhhddhdmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("mddddmmmdmmddddddddddddddddddddddddhhhhhhyyhhhhhddmmmmmmmddddhooooooodmmmNmsyhdmmmmmmmmmmmmmmmmmmmmmmmmmmmNNho++///////+++++o+ooooosydmNNMMMMMMMMNMMMMMNNNNNmmmdhys+:/:-. `---.:osyydNMMMMMNNmmddmmmddhhhhhhhhhhhddddmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("dmddddmmddddddddddddddddddddddddddhhhhhhyyyyhyyhddmmmmmmmmddhhooooooohhyhhhhysshhddddhhdNmmmmmmmmmmmmmmmmmmNNds+//////////++++ooooosssshhmNNMNNNNNNNMMNNNNNmmNNmmmdhyhhhhsydmNNNNMMMMMMNNmmdddddddmddhhhhhhhhhhhhhddmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("ddddddddmmdddddddddddddddddddddddddhhhhyhyyyyyyyhdddmdmmmddhhhoooooooysosooosyssssssyyymNmmmmmmmmmmmmmmmmmmmNNds+++/////+/////+++osyyyyssyhhddmNNNNNNNMMMNNMMMMMMNNNNMMMMMMMMMMMMMNNNNNNmmmmmddddddddhhhhhhhhhhhhdddmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("ddddddddmdddddddddddddddddddddddddddhhhhyyyyyyyyyyhdmmmmmmddhhsssssssyhhhhhhdyooosshmmmmmmmmmmmmmmmmmmmmmmmmmmhhy+/////+//////+///ossyysyyyyssyyhdmNNmNNNNNMMMMMMMMMMMMMMMMMMMmmdhyssdNNNNNmmmmmmddddhdhhhhhhhdhddddmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("ddddddddddmdddddddddddddddddddddddddhhhhyyyyyyyyyyyhNNMMMMMMMNNNNNNNNNNNNNNNNhssydmhdddmdddddmmmmmmmmmmmmmmmmmdysys+/////////+o++++/osoyosysossysyydysyhydmNmmmNmNNNNNNNmdmdmhysssssssdNNNNNNNmmmmmdddddddddddddddmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("ddddddddhddddddddddddddddhddddddddhhhhhhhyyyysssssssyyyhhdmmNMMMMMMMMMMMMMMMMMMNNMNNNNmmmddddddmmmmmmmmmmNMMMMNmhyssss++////+oooo+++++sooososssshyso+osooyhhyddhddhsyyydyssyssssssyyyssymNNNNNNNNmmmmmmmddddmdddmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("ddddhdddhhddddddddddddddddhhhddddddddhyssooooooooooooooossyyyyhdNMMMMMMMMMMMMMNMMMMMMMMMMMNNNNmmmmmmmmmmMMMMMMMMMNmyyosyso+/++++oooooo+syyysssssssoo+osshddmshdmddhddmhyysso++osyso++ososdNMNNNNNNNNNmmmmmmmmmmmmmNNNNNmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("ddddhhdddhhhddddddhddddddddhhhhhhddhyssoo++++++++++++++oooosssssshmMMMMMMMMMMMMNNNNMNMMMMMMMMMMMMMMMNNNNMMMMMMMMMMMNmdyosooooosoo+++ooo+ssssso+++++ooooooosssyhsyhsssyhyyyssooso++++ooossssdNMMNNNNNNNNNNmmmmmmNNNNNNNNmmmmmmmmNNNNNNNNmmmmmmmmNNNNNNNNNNN"))
ninja.append(list("dddddhhdhhdhdddddddhddddhhddhhhhddhysoo+++/////++++++++++oooooosssshNMMNNMMMMMMMMNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhyo++osso++/++/+oooo++++++oyso/+++o++/o+yooohysso++oooosoooooooshhdddmNMMNNNNNNNNNNNNNNNNNmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNN"))
ninja.append(list("ddddhhhhhhhhhhhdddhdhhdddhhdhhddhyssoo++//////////+++++++++++ooooooosdMMNNNMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhyyyhhhyyyyssyyyssyyyhhyyhyso++soo+oyhyooo+//////+++oosyyhmNdhyyyhNNNNMMMNNNNNNNNNNNmmNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNN"))
ninja.append(list("ddddhhhhhhhhhhhhdddhdhhdhdhhddhyssooo++///////////++++++++++++++oooooohNMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMNmdhysoosssssssssoosyyysyhdhyhhhssoo++++++"))


skurk = []
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNNNMNMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMNNNmmmmNNNNNNNNNMMMNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmddhhhyyyyyhddmmmmNNMNNNMNMNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhyssoo++++++++oyssyhdmNNNMMMMMMNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmmdhysoooo++//::::::::///+++sydmNNMMMMMNNMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMNNmmNmdysooooo++///::-----:::://+++osyhmNMMMNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNmNNmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMNNmNNNmhysso+//::::-----------::/++oosooymNNNNNNNNNNNMmmmNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNNM"))
skurk.append(list("MMMMMNmNNmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMNNmNMNmhyso+/:::-----....-----::://++ossshmNNNMMMMMMMMmdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmN"))
skurk.append(list("MMMMMNmmmmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMNNMMNdhso+//:::----.......-----:://++ossydmmNMMMMMMMMdhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNm"))
skurk.append(list("MMMMMNmmmmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMNmyo+/::--......```````.....--::/+syhhmmNMMMMMMMMhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm"))
skurk.append(list("MMMMMNmmmmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMNmyo+++/:-...`````````````.-:////+symdNmNMMMMMMMMysNMMMMMMMMMMMMMMMMMMMNNNmhshmdmdmNMMMMMN"))
skurk.append(list("MMMMMNmmmmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMNmmhso+////:-.```````````.--:::/+++sydmNNNMMMMMMMMyoNMMMMMMMMMMMMMMMMMMNNmdhyohmmmhmNMMMMMM"))
skurk.append(list("MMMMMNmmmmmmNNNNNNMMMMNNNNNNNNNNNNMMMMMMMMMMNmmy+:-..--:/:-..``````.----.....-/shhmmMNMMMMMMMMyoNMMMMMMMMMMMMMMMMMMNMMMMMMNMMMMMMMMMMMM"))
skurk.append(list("MMMMMNmmmmmmmNNNNNMMNNNNNNNNNNNNNMMMMMMMMMMMNNh+:::::::://::-.```..--::::::---:/yhdmNMMMMMMMMMysNMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNmmmmmmmNNNNNMMMNNNmmmmNNNNMMMMMMMMMMMMNmo//oo+sso--:/+/-...-::::-:+o+/+/::+hhdNMMMMMMMMMhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNmmmmmmmNNNNNMMMNNmmmmmmNNNNNNMMMMMMMMNmy+/oo+/sys-.-:++:---:/:--./yyo:+o/:/yyydMMMMMMMMMdhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMmmmmmdmNNNNNMNNNNNNNmmmmNNNNNMMMMMMMMNms+/++/::----:/+//:::://:-----::://:/oy+hMMMMMMMMMmdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMmmmmmdmNNNNNMMMMMMMMMMNNMMMMNMMMMMMNNmms+//::::---:+o+/::--:///:::::-:::://oo:oMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmddmMM"))
skurk.append(list("MMMMMMmmmmmdmNNNNNMMMMMMMMMMNNMMNNMMMMMMMNNNmy+/:::----:+o++/::-::/://-----:::///o++yMMMMMMMMMNmMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdyo++hmNMN"))
skurk.append(list("MMMMMMmmNNmmmNNNNNMMMMMMMMMMNNNNNMMMMMMMMMdNmyo/:--....:/oso/:-:://///-....---://o+sNMMMMMMMMMNNMMMMMMMMMMMMMMMNNmdhhhhyyso+++:/:/ymMNN"))
skurk.append(list("MMMMMMmmNNmmmNNNNNMMMMMMMMMMNNNMMMMMMMMMMMmmNho/:--....-+ss+:-..-:/++/-......--:/o+dMMMMMMMMMMNNMMMMMMMMMMNmhssoo+//:::::::://:::/omNNm"))
skurk.append(list("MMMMMMNmNNmmmNNNNNMMMMMMMMMMNNMMMMMMMMMMMMMNNdo/:--...-/soo/:-..--://+:......--:/sdNMMMMMMMMMMNNMMMMMMNdyo+/::::::::---:::::::::::/hmNm"))
skurk.append(list("MMMMMMNmNNNmmNNNNNMMMMMMMMMMNNMMMMMMMMMMMMMMMms+:-----:/ooooo/::://///:-------:/+dMMMMMMMMMMMMNNMMMMmy+/:----------------::::::::::+hNm"))
skurk.append(list("MMMMMMNmNNNmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMNho/:::::/+//////+/::::://::::::::/sNMMMMMMMMMMMMNMMMMho/:--...------::://:///++/::::::+hN"))
skurk.append(list("MMMMMMNmNNNmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMms/:::/+oo+/:--..-..-:://+/:::::/omMMMMMMMMMMMMMMMMNy+/:-.......----oysoooooooss+::::::+h"))
skurk.append(list("MMMMMMMNNNNmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdo:--/+shy++///:::://+oso+/:-:/+hMMMMMMMMMMMMMMMMNy+/::-.......---:osooooooooooo/::::::+"))
skurk.append(list("MMMMMMMNNNNNmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho:-:/+sy+/::.--.--::+s+/:--:oyMMMMMMMMMMMMMMMMNy/+:-::.......--/syysoooooooosso/:::::/"))
skurk.append(list("MMMMMMMNNNNNmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+::/osso++::/::-/++ss+::-:ohNMMMMMMMMMMMMMMMMh:+/--::.......-+yyyyysoooooooosso/::///"))
skurk.append(list("MMMMMMMNNNNNmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMNNh+:/+yyoo+//:::/+oos+/:-:ohMMMMMMMMMMMMMMMMMm+-+:-.::-....--/syyyyyysooooososssy+////"))
skurk.append(list("MMMMMMMNNMMNmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMMNmmmy+:+ossoo+::::/+o+//:-/oyNMMMMMMMMMMMMMMMMNy::/:-.::---.--:ssyyyyyyyysoossssymMmo//+"))
skurk.append(list("MMMMMMMNNMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNddmmho/++++//////:::/:::/symMMMMMMMMMMMMMMMMNys--/:--::-----:oyyyyyyyhhhyssssydNNNMNo++"))
skurk.append(list("MMMMMMMMNMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhdmho++//::-----::::/+ssyNMMMMMMMMMMMMMMMMhoo--+---:/-----:shhyysyhhhhhhyshNMMMNNMNs+"))
skurk.append(list("MMMMMMMMNMMMNNNMNMMMMMMMMMMMMNMMMMMMMMMMMMNNmNmmdhysyddyo+/::-----:::/ossshdmmmNNNMMMMMMMMMdoos--/:--:+:--::-:yyyyyyhhhhhhydMMMMMMMNNNh"))
skurk.append(list("MMMMMMMMNMMMNNNMMMMNMMMMNNNNNMMMMMMMNNmmddhddNmmdhyssosddyo++/////++oooosshdddhhhhhdmmNNMMN+++y:-:/---+/:-:/::syhhyyyhhhhyssdMMMMMMNNNM"))
skurk.append(list("MMMMMMMMNMMMNNNMMMMNMMMMNNMMNNNNmmmddhhyyyhddmdddhyssoo+ossssysssoo++++osyhdhhhhyyyyyhhhdmdyyyhs+/o/:-/o/:://+hhhhhhhyhyssssshNMMMNMMMM"))
skurk.append(list("MMMMMMMMNNMNNNNMMMMNNMMNNNNNNNmmmdddhhyyyhhhddddhyyssoo++///////////+++ossyhhhhhyyyyyhhhddmmmdddddddhyyhyo+ooosdddhhhyssssyyyyhmNNMMMMM"))
skurk.append(list("MMMMMMMMNNNNNNNNNNNNNNNNmmmmmmmmmmmdddhhhhhhdhdhssssssoo++//////////++ossoshyyhhhhhhddddddddhhhhhhhhhhdddddhhsoohddhyyyssyyyyyyydMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMNNNNNNNNmmmmddmdddmddddddmddddddhyhsoosssoo++++///////++oooo+yyyyhhhhhhhhhhhhhhhhyyyyyyyyyhhhdddmdyohyyyyyyyyyyyyyyhdNMMMM"))
skurk.append(list("MMMMMMMMMMMNNNNNmmmmmdddddddddddddddddddddddhhyyhsossssoo++++++///++ooooosysyyhhhhhhhhhhhhhhhhhyyyyssyyyyhhhhdddmmdhhhhhhhyyhhhhhhdNMMM"))
skurk.append(list("MMMMMMMMMMNNNNmmmmmddddddddddddddddddddhhhhhhhyyyhsssssoo++++++++++oosooshyyyyyhyhhhhhhhhhhhhhhhyyyyyyyyyyyyhhhddmmmhhhhhhhhhhhdddddmNh"))
skurk.append(list("MMMMMMMMMNNNNmmmmmddddddddddddddddddddddhhhhhhhhhhdyyyssooo+++++++oosssshhyyyyyyyhhhhhhhhhhhhhhyyyyyyyyyyyyyyhhhddmmmmhdddddddddddmmMMd"))

hagge = []
hagge.append(list("mmmmmmmmmmdmmmdmmdmNNNNNNNNNdmNNNNNNMNddmmdhdmdhddyoyho:+hoohmhydmdhdds+oyshmNMMMNmdyo+-..://:::::/:"))
hagge.append(list("dmmddddddddddddddddmNNNNNNNNmNNNNNNNMNmdmmddmmdhdmysyh+:+yoohmyshdhydds+syoymMMMNNmdyo+-..::::::::::"))
hagge.append(list("mmmmmmddddddddddddmNNNNNNNNMNNNNNNNNNNmmNNmdmmdhdmhyhhs+oysshdhydmdhddsosyoymNMMMmddyo/-..::::::::::"))
hagge.append(list("mmmdmmmdmmmdmmmdmmmNNNNNNNNNNNNNNNNNNmhyhdhyhhssssoo+o+/+oo++osyhmmmmmmddhhmNMMMNmddyo+-..:/::::::::"))
hagge.append(list("mmmdmmddmmddmmdddmmNNmNNNNNNNNNNdhhyys+osssoooo++++++++//osoossoosyyhhddhhhNNNMMNmhhyo+-..://:////::"))
hagge.append(list("mmmdmmddmmmdmmdddmmNNmNNNNNNmdysooo++oooo+o++++++///::::::::::::://++ossssymNNNNNhsooo+-..-:::::::::"))
hagge.append(list("mmmmmmmdmmmdmmdddmmNNmNmNNmhsso++++oo+++//+///+/++///:::::::::::--:-::/+oosddmmNNdysss+-.`.........."))
hagge.append(list("mmddmmddmmmdmmdddmmmmmmmhssyhhhsssooo+++/////+++o+++++/////////:/:///::::/+yhddddhhhhs/-..::--------"))
hagge.append(list("mmddmmddmmddmmdddmmmmdyoyhhdhhysoo++oo++oooo++//////////++/+++++///++o++////+ohddysyyo/..-//////////"))
hagge.append(list("mmddmmddmmddmmdddmmhssosyoshhyyyyhhhhyhhyssoooo++++++///////+oso+++++oosyyo+//oyhysyyo/..-:::///////"))
hagge.append(list("mmddmmddmmddmmdddhsosyyyso+++oooooooo+ooossyyysoo+++oo+++/++++ossoo+++oosyyys+////+ooo/..-::/::///:/"))
hagge.append(list("mmddmmddmmddmdyyyyooodddhso+//+oooossssssooo+++ossooo+++++oooo++++ooooosssysyys/////+/:-.-://:://///"))
hagge.append(list("mmddmmddmmdddyssssys+ydmddhyssooooossyyyyyyyysoo++++ooooo+++++oo+//+oossoossooss+///++/:--:/:://////"))
hagge.append(list("mmddmdddmdhhsoyyo+/+sooyhdhhyyyyysssssooooooooooooo++/++ooooo++ooooo+osssssso++ooo++oooo/:///://////"))
hagge.append(list("mmddmdhdhyo++shhyo+++ssooyysyyyhhhhyyysssooo+++++++++++++++++osssssyyssyyyyyyso+oossoosoo+/:::::::::"))
hagge.append(list("mdddmdhyo:/+osssyys+ooo++++ooossooooooooo+++/////////+++oo+ooooosssyyhyhhhhyyhys++osysos+::---------"))
hagge.append(list("mdddmhyo////syyssssooooo+oooooooo++++++oooo++////:/://///+ossssssssyyyyyyyhhhhhhyooosyoso:-........."))
hagge.append(list("mddddho/:/++ossssyyyyyyyyyyyyyyyyysssoooo++////////////++++oosyhhhhyyssssssyhhhhdhysosyso-...```````"))
hagge.append(list("mdddho/+/++oooososyyhhhhhhyhhhhhhyyssoooossssso+++++o+++++++oosyhhhhyyyyyyysyddhdddhyssyo:.`.```````"))
hagge.append(list("mdhhsoso//+oo++oooossyyhyhhhhyyyysssssyyyyyyyyyhhddddysoo++++++oossyyyyyhhhhhyhddddhysssy+-.````````"))
hagge.append(list("mddddyo///+/++/+oossysssssysyhhyyyyhhdddddddddddmmmmmmmmhhyso+++++oosyyyhhdhddhhdhhysysoyo-.````````"))
hagge.append(list("ddddho+/:/://///+osoyyyyyyyysoo++o+oooyyyhddddmdddmmmmmmmmdyyso++++osyyhhhhhhddhhhhs++soso-.`.``````"))
hagge.append(list("ddhhyo/:/://:///+oo+osyyyyhhhhyysssssssyyyyyyyhhhhhddddmmddddyo++//+oyyyhhhhhhhhhyso++++oo:--......."))
hagge.append(list("mmmdys/:://://+//+oo//osssssyyyyhyyyyysooossssssyyyyyhhddddddhhys+/::/oyyhhhyyhyysyso+oo++ossssoooso"))
hagge.append(list("mNNdho+/:///+o+://+o+//+o+ossoossyyyyssoooooooosossyyyyhhhhhddhhhyso+///osyyyyyyossss+ooo+oyhhhhyyhs"))
hagge.append(list("mNNdhsso++/+oys//+++//+++++oyssooosyyyssoo+++ooooosssssyyyhhhhhhhyyysoo+++osyyyss+osss++ooosyyhhyyho"))
hagge.append(list("dNNmdyys+o+sohy+++o+++/oooo+osysooooossssooo+++oooooosssssyyyyyyyhyyysoooyyyssssssoyyso++ossyyhhyyy+"))
hagge.append(list("mmNNmmdyoo+hhoy++++oo+++osoo++osssoooooooooo+o+o+++oooooossssyyyyyyyyyyssooyddysssoshyssoosyyhhhhyy+"))
hagge.append(list("NMMMNNhyhs+ydoso+++++++++ooooo+oosooooo+ooo+++++++++++ooooooosssssssssssyhhyshdhyysyhhhssoshhhhhhhy+"))
hagge.append(list("MMMMMNddhhyohhyo+++++++++oooooo+oooooooo+++++++++++++++++++ooooooooooooosyhdddddhyhhhhhhysshddhhhhy+"))
hagge.append(list("MMNMMMNNdhhsydds++++++ooooooosoosoooooooooooooooooooo++++++oo++++ooooo++osydmmdddhhddhhhhysssssssss/"))
hagge.append(list("MMMMMNNNdhdhhdds/+//+ooossssssysssssooosssoossssssooooooo+oo++++++++++++++oydmmdhyhdddhhhhsoooooooo/"))
hagge.append(list("MMMMMMMNhhddmddo/++osyhhhhhhhyyhyyyyyssyhysssyyhhhhhhhhhyyysssoooo++///////oydddhyyydddhyhhyhhhhhys/"))
hagge.append(list("MMMMMMNdsydddddo/osyyhhhhhddmmmmddhhyssoosssyhdddddddddhhyyysssssso++//////+shdddyssyhdhyyhyysssyys/"))
hagge.append(list("MMNMMMNdyyhddddo/+oyhddmmNmdNNNNNNNmdys++/+oshhdmmmhhmNNmddddhhhyys+////:://ohhhhhysssyyyyyoo++osyo/"))
hagge.append(list("NMNMMNNNdyyhhhhs/++syhdhhhhhdmmmmmmmmyo/::/+syyyhddhyhhhhyyyyyyyso+/:::::://oyyyhhyssyssyyo+/://+o+:"))
hagge.append(list("MMNNNNNNNdhhyhhs////+++osyyyhhhdddddds/::://+ossyyhhhyyysooo++////:::::::://ossyyhyssyosy+-.`````..`"))
hagge.append(list("MMMNNNmmNMNdyyyy+//:::/++ossyyyyyyyys/::::://++++oosssooo++//::::----::::///oosyyhysso+yy/--.......`"))
hagge.append(list("MMNNNmmmNNMmyhdyo//:::///++++ooooooo+:::-:://///////+++////:::::::-:::::://++oyssssoo+oyy+:::::::-.`"))
hagge.append(list("NNNNmmmNNNNNNmmdo////////////////++/::::::::::::::::::////:::::::::::::////+/sy+/+o++ooss+/:::::::-."))
hagge.append(list("NNNNmmmmNNNNMNmmh++///:::::::////++::::::::::://:/::::::::::::::::://////////+///+//o++oo+::::::::-."))
hagge.append(list("NNNNmmmmmNNNNNNmms++/////::://++os+:::::::::::/+++///::::::::::::////////////:/:://oo++oo+:::::::---"))
hagge.append(list("MNNNmmmmmmNNmNNNmh+++++/////++osyo:::::----:::::+oo++//::::::////////////////////oydhhhhys/::::::-.."))
hagge.append(list("MNNNmmmmmmNNNNNMNNs++o++++++oosyy+++////::////::/+sso++/////////////////////+shddmmmmmNNNNy::::::/+s"))
hagge.append(list("MNNNmmmmmmmNNMMMMMdooooooooossyyssyyysssooyhhyoooo++ooo++//////++++/////////+sMMMNNNNNMMMMN/:/+syyhy"))
hagge.append(list("MNNNmmmmmmmNMMMMMMNoosoosssssssssssyhdhhyhhdddhso+///+oo+++/////+++/////////+sNMMMNNMMMMMNNhhdmmmmmm"))
hagge.append(list("NNNMmmmmmNNMMMMMMMMyoosssssssoo+++ossyhhhhyysoo+///::/+++++++++++++//////////yNNMMMNMMMMNNNNNNNNMNNN"))
hagge.append(list("NNNMNmmmmNNMMMMMMMMmoooossssoooooooooossssooo+++///////+//++++++/+/////////+/yMNNMMMNNNMMMMMMMMMMMMN"))
hagge.append(list("NNNMNmmmNNMMMMMMMMMNsoooossoosysoosyyhyyssyyso+++//+oo++o+/++++///////++++++/hMNNNMMMMMMMMMMMMMMMMMM"))
hagge.append(list("NNNNmmNNMMMMMMMMNNNMmooooooosyhdhhdddhddddddhhhhhhyyhhyso+//////////+++++++//dNNNNNNNMMMMMMMMMMMMMMM"))
hagge.append(list("NmNmmNNMMMMMMNNNMMMMMhoooooosssoooosyyyyysssssooo+++++osso+///////+/++++oo+//mNNNNNNNmNNMMMMMMMMMMMM"))
hagge.append(list("NmmmNNMMMMMNNMMMMMMMMMyoooossoo++oossyyhhhhhyysoo++////+oo+++//+++++++oooo/:+NNNNNNNNNNNNNMMMMMMMMMM"))
hagge.append(list("NmmNNNMMNNNMMMMMMMMMMMNyoosssooooooosssyyyhyyssoo++++++++++++++++++oooooo+//yNNNNNNNNNNNNNNMMMMMMMMM"))
hagge.append(list("mmNNNNNNNMMMMMMMMMMMMMNNyossssooooooo+oooooooo++++++++++++++++ooooosssoo///+mNNNNNNNNNNNNNNmNMMMMMMM"))
hagge.append(list("mNNNNNNMMMMMMMMMMMMMMMMMMyosssoo+++//////////::::://///+/+++oooossssso+///+hNMNNNNNNNNNNNNNNNMMMMMMM"))
hagge.append(list("mNNNNMMMMMMMMMMMMMMMMMMNNhoosssoo++/////+++///:::::////++ooosssyyssso+///+sNMNNNNNNNNNNNNNNNNNMMMMMM"))
hagge.append(list("NNNNMMMMMMMMMMMMMMMNMNhydy++osssso+++ooooo+oo++//++++++oosssyyyysso++//++smNNNNNNNNNNNNNNNNNNNNMMMMM"))
hagge.append(list("NNMMMMMMMMMMMMMMMMNMh+oyds+++oyyhyyyyyyyyssysssooyyssosyyyyyyyyso++++/++odNNNNNNNNNNNNNNNNNNNNNNMMMM"))
hagge.append(list("NMMMMMMMMMMMMMMMMMMs:+shmo++++osyddddmdddhhhhdhhhhdhhddddhyyysoo+++++++shNNNNNNNNNNNNNNNNNNNNNNNNMMM"))
hagge.append(list("MNMMMMMMMMMMMMMMMNy-/oshms+++++oosydmmmmdddddmmmmmmNmmddhyssooo+++++++oymMNNNNNNNNNNNNNNNNMMNNNNNNMM"))
hagge.append(list("MMNMMMMMMMMMMMMMMh-/+oymdyo+++++ooossyhhhdmmmmmmmmmddhyysssoooo++++++osdNMNNNNNNNNNNNNNNNNMMMNNNNNMM"))
hagge.append(list("MMMMMMMMMMMMMMMMm::/+oymdyo++++++oooossssyyhhhhhhyyysysssssooo++++++osyNNNNNNNNNNNNNNNNNNNMMMMNNNmNN"))
hagge.append(list("MMMMMMMMMMMMMMMNo.:/+ohmhyso++++++ooossssssssyysssssssssooo++++++++ooydMNNNNNNNNNNNNNNNNNMMMMMNNNNNN"))
hagge.append(list("MMMMMMMMMMMMMMMm--///+ddhyssoo++++oooosssssssssssssssooooo++++++++oosyNMMNNNNNNNNNNNNNNMMMMMMMNNNNNN"))
hagge.append(list("MMMMMMMMMMMMMMMs.-::/+ddhysssooo++ooooooossssssssoooooooo+++++++ooos+dMMMNNNNNNNNNNNNMMMNMMMMMMNNNNN"))
hagge.append(list("NMNMMMMMMMMMMMm-.-::/oddysssoooo++++ooooosssooooooooooooo++++++ooss++NMMMMMMNNNNMMMMNNNMNMMMMMNNNNNN"))
hagge.append(list("MMMMMMMMMMMMMNo`---:/+dhysooo++++++++oooooooooooooooooo+++++++oooo/:mMMMMNNNNMMMMMMMMNNMMMMMNNNNNNNN"))
hagge.append(list("MMMMMMMMMMMMMm-.----:+hysoo++//////+++++oooooooooo++++++++///++++--yNMMMNNNMMMMMMMNNNMMMMMMMNNNNNNNN"))
hagge.append(list("MMMMMMMMMMMMN+`.----:/yso+++////::///+++++++++++++++//////////+/..sNMMMNNNMMMNNNNNNNNNMMMMMMMMNNNNNN"))
hagge.append(list("MMMMMMMMMMMMh``.-----/yso++////:::////////+++/////////////////:`.omNMMNNNNNNNNNNNNNNNNNMNNNMMMMMMNNN"))
hagge.append(list("MMMMMMMMMMMm:``.--..-:oo+++////::::://///////////////////////-``/yNMNMMMMNNNNNNNNNNNNNNNNNNNNNMMMMNN"))
hagge.append(list("MMMMMMMMMMNo ``......-/oo++////:::::::::::::::::::///::/://:.``:omMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMN"))
hagge.append(list("MMMMMMMMMMd.```......../o++/////::::::::::::::::::::::::::.```:/yMMNNNNNNNNNNNNNmmNNNNNNNNNNNNNNNNNN"))
hagge.append(list("MMMNMMMMMMh:/:......``.-o++////:::::::::::::::::::::::::-````./oNMNNNNNNNNNNNNNNNNNNNMMNNNNNNNNNNNNN"))
hagge.append(list("MMMMMMMMMMNh+oo-.``````.+++////:::::::--::-------::::::` `:///:dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("NNNMMMMMNMMMmso/-``````..++///:::::-:------------::::-`  -syyosNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("NNNNNMMMMMNNMMs:/:...````-+///:::::-------------:--.````-oss+hNNNNNNNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("NNNNMMMNNNNNMN+-/++++/:.``-///::::---------------.``.:/+o+++hmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("NNMNNNNNNNNNMN/-:/++++/:-...--::::-------------..-:/++///+sdNNNNNNNNMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNM"))
hagge.append(list("NNmNNNNNNNNNMN:.-:///+++:-.````.:::----------.``--://///odNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("mmmNNNNNNNNNMm:`.--:::://:--.`  `.:--------.````.-/:::ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNN"))
hagge.append(list("mmNNNNNNNNNNMd-```.....---://-.`  .::----.`  `.-::--:yNMNNNNMMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMM"))

logo = []
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNmmdhhyyyyyysoyyyyyyhhhmmNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNmdhys+/////:::::::::::::::::::////+oshhmNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNdhso+//::::::::::::::::::::::::::::::::::::://+shdmNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNdyo//:::::::::::::::::::::::::::::::::::::::::::::::://+shmNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNdyo//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::/+shNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNdy+/:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://ohmNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNdy+/::::::::::::::::::::::::::::::::::::::::::::::::::++////:::::::::::::::/ohNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNmho/:::::::::::::::::::::::::::::::::::::::::::/+ossssssshddhyyyyso/:://:::::::::+sdNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNdy/::::::::::::::::::::::::::::::::::::::::::::+syyyyssssssyyyyyssyyyyyo+hyo/::::::::/odmNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNdo/::::::::::::::::::::::::::::::::::::::::::::/syssssssssssssssssssssssyyydyyh+::::::::::+hNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMNNNNNNNNdo/:::::::::::::::::::::::::::::::::::::::::::::+dhhdhysssssssssssssssssssssyyssyd+:::::::::::+hNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMNNNNNNNNds/::::::::::::::::::::::::::::::::::::::::::::::+osmdhyyssssssssssssssssssssyyyyyshh:::::::::::::+hNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMNNNNNNNmy/::::::::::::::::::::::::::::::::::::::::::::::::/ydyysssssssssssssssssssssssyssyyyhh:::::::::::::::odNNNNNNNNMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMNNNNNNNNd+::::::::::::::::::::::::::::::::::::::::::::::::::/myysyssssssssssssssssssssssssyssyd+::::::::::::::::/ymNNNNNNNMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMNNNNNNNms/:::::::::::::::::::::::::::::::::::::::::::::::::::/dyssssssssssssssssssssssssssyyyyh+:::::::::::::::::::+dNNNNNNNNMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMNNNNNNNNd+:::::::::::::::::::::::::::::::::::::::::::::::::::::/hyysssssyyyysyssssssssyyssssyyymo:::::::::::::::::::::/yNNNNNNNNMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMNNNNNNNNy/::::::::::::::::::::::::::////:::::::::::::::::::::::::/hyyssyydhysyhysssssssssssssssyhh/::::::::::::::::::::::omNNNNNNNMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMNNNNNNNNy::::::::::::::::::::::::/+shyyyyhso+//::::::::::::::::::::+hyyyydy:::omyssssssssssssyyysyyhs/:::::::::::::::::::::+mNNNNNNNMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMNNNNNNNNo::::::::::::::::::::::/+yhy/.    .:+syhyo+//::::::::::::::::ohyyyd:::/yysssssssssssssyyyyyyyyhs+/:::::::::::::::::::/dNNNNNNNMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMNNNNNNNNo::::::::::::::::::://ohhs:`            `-/syhys+//:::::::::::+dsyd/::yhyssyyssssssssssyysyyyyyyyhyo/::::::::::::::::::/mNNNNNNNMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMNNNNNNNs:::::::::::::::::/+shh+-                     `-/sNms::::::::::yhhh/::yNdyysyssssssssssssssyyyyyyyyyhh+::::::::::::::::::/mNNNNNNNMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMNNNNNNNs:::::::::::::::/oyds/`                        ./ymNyN/::::::::/so/::::shhddyyssssssssssssssyyyyyysyyyyhs::::::::::::::::::/mNNNNNNNMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMNNNNNNNy:::::::::::::/sdho-                         -odNmhd:`dy::::::::::::::::yyyyyysssssssssssssssssyyyyyyyyyyhh/:::::::::::::::::+NNNNNNNNMMMMMMMMMMM "))
logo.append(list("MMMMMMMNNNNNNNd/::::::::::+ydy/`                        `/ymmdhyhd.  +N:::::::::::::::+-``shssssssssssssssssssyyyyyyyyyyyhh::::::::::::::::::sNNNNNNNMMMMMMMMMMM "))
logo.append(list("MMMMMMMNNNNNNN+:::::::/ohhs:                         .+hNmhyyyydy`   `No::::::::::::::+   `hysysssssssssssssyyyyyyyyyyyyyymo::::::::::::::::::hNNNNNNNMMMMMMMMMM "))
logo.append(list("MMMMMMNNNNNNNs:::::+sdNmo-`                      `:smmdhyyyyhdmh      sd:::::::::::::+/    /hyyssssssssyyyyyyyysyyyyyyyyyydy::::::::::::::::::/mNNNNNNMMMMMMMMMM "))
logo.append(list("MMMMMNNNNNNNd/:::ody/:-:+syys/-`              .+ymmdhyyyyhdmNNNN:     -M+::::::::::::+:    .dsssssyyyysssssssyyhyyyysssssydy:::::::::::::::::::sNNNNNNNMMMMMMMMM "))
logo.append(list("MMMMMNNNNNNNs:/sds:.........-/oyys+:.     `:odmdhhyyyhdmNNmNNmNNm`     hy::::::::::::/+//` `dssyyhs++++++++++++oshhyyyyyyymh:::::::::::::::::::/mNNNNNNMMMMMMMMM "))
logo.append(list("MMMMMNNNNNNm/ydo-................-/oyhyo/ymmdhhyyyhdmNNNNmdNNNNNNs     /N/:::::::::::/mNNh.`dyhyo+++++++++oo++++++odhyyyyymo::::::::::::::::::::yNNNNNNNMMMMMMMM "))
logo.append(list("MMMMNNNNNNNmho-.......................-/NNhyyyhhdNNNNNNmmmNNNNNNNN.    `ms::::::::/osshNNN/:myo+++++++osydysy+++++++dhyyhms:::::::::::::::::::::+NNNNNNNMMMMMMMM "))
logo.append(list("MMMMNNNNNNNo............................yNyddmNNNNdmhmNNNNNNNNNNNNyys+++hdo+o++ossso+++dmh+s+/+++++++++sdd++o+++++++ymdmh+:::::::::::::::::::::::dNNNNNNMMMMMMMM "))
logo.append(list("MMMMNNNNNNN+............................/MoommddmNNNNNNNNNNNNNNNNNm/osoooosooo++++++++++syo///+++++++shmdo++++++++++hho+:::::::::::::::::::::::::sNNNNNNNMMMMMMM "))
logo.append(list("MMMMNNNNNNNmdo-..........................mh+hmdNNNNNNNNNNNNNNNNNNNN``./+s+++++++++++++++++///+//+oshhdds+++o++++++ohy/:::::::::::::::::::::::::::oNNNNNNNMMMMMMM "))
logo.append(list("MMMNNNNNNNdNmmds:........................oN+oNNNNNNNNNNNNNNNNNNNNNN-   `:yhysoo+++++++++++++osyhdhhhhs++++yhssssyddo:::::::::::::::::::::::::::::/NNNNNNNMMMMMMM "))
logo.append(list("MMMNNNNNNNsyNmmmmy/......................-Ny+hNNNNNNNNNNNNNNNNNNNNN:     -No+osssssssssssssoo+sdNhho+++oyhmmhhyyymyooo+:::s/:::::::::::::::::::::/NNNNNNNMMMMMMM "))
logo.append(list("MMMNNNNNNNs/dNmmmmmh+-....................yN+oNNNNNNNNNNNNNNNNNNNNho//-` `ms:::::::/::::::::::hsho++syhds/oNysyyyd```-oy++No:::::::::::::::::::::/mNNNNNNMMMMMMM "))
logo.append(list("MMMNNNNNNN+:+mmmmmmmmdo:................../Mo+dNNNNNNNNNNNNNNNNds/...-://:sm/::::::::::::::::so+osysooo-``:sosyyyh:.` `/oymys/:::::::::::::::::::/dNNNNNNMMMMMMM "))
logo.append(list("MMMNNNNNNNs::oNmmmmmmmmds/.................md+sNNNNNNNNNNNNNdy/-.........:omd+:::::::::::::::yoys+/::o`      `-:..``     .d///:::::::::::::::::::/NNNNNNNMMMMMMM "))
logo.append(list("MMMNNNNNNNs:::yNmmmmmmmmmmh+-..............sMo+mNNNNNNNNmds/-..........-:..-ody+:::::::::::::///:::::s:    `-`           `h/:::::::::::::::::::::/NNNNNNNMMMMMMM "))
logo.append(list("MMMNNNNNNNy:::/hNmmmmmmmmmmmds:............-Ny+yNNNNmds+:...........-/sddhss/:ohh+::::::::::::::::::o:` `-+shy/--/.    /oyy::::::::::::::::::::::/NNNNNNNMMMMMMM "))
logo.append(list("MMMMNNNNNNd::::/shmmmmmmmmmmmmmy/...........hm+omds+:....--::::--:oydmNNNmmhd+/+ydho/::::::::::::::/y:+syyyyyyyyyhy+::+hydy::::::::::::::::::::::sNNNNNNNMMMMMMM "))
logo.append(list("MMMMNNNNNNm/::::::/sdNmmmmmmmmmmmh+-........+Noy+.....-/++/::..`.-odNNmmsoo-.-.`.:shho/://:::::::/syhhyyyyyyyyyyyyyyyyyyydh::::::::::::::::::::::yNNNNNNMMMMMMMM "))
logo.append(list("MMMMNNNNNNNo::::::::+dmNNmmmmmmmmmmdo-......-Nhh...../s/-:/:.      .yNh-           .:sh+::s+//+oyhhyyyyyyyyyyyyyyyyyyyyyyhm/::::::::::::::::::::/mNNNNNNMMMMMMMM "))
logo.append(list("MMMMNNNNNNNh::::::::::+shmNNNmmmmmmmmmy:.....dMo..../ds/:--.        `s/-//:`        `/o`.shdhyhyyyyyyyyyyyyyyyyyyyyyyyyyyymo::::::::::::::::::::oNNNNNNNMMMMMMMM "))
logo.append(list("MMMMMNNNNNNN/::::::::::::/oymNNNmmmmmmmmh/...oM+.../+h+//:.````      `sho+h/      ``-m+ohdhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhm/:::::::::::::::::::hNNNNNNNMMMMMMMM "))
logo.append(list("MMMMMNNNNNNNy::::::::::::::::+sdNNNmmmmmmmdo-.hd-.o+-hm- +osyh.      `s/` .h://+oosyhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydh/:::::::::::::::::+NNNNNNNMMMMMMMMM "))
logo.append(list("MMMMMMNNNNNNm/::::::::::::::::::/ohNNNmmmmmmds:ym/:odNmo`o++hmd/.`` `o:  .shhyyyyyyyyyyyyyyyyyyyyyyyyhhhhyyyyyyyyyyyyyyyyyyydy:::::::::::::::::hNNNNNNNMMMMMMMMM "))
logo.append(list("MMMMMMNNNNNNNh:::::::::::::::::::::/+ymNNmmmmmmysddo:+yyhhyhmNdhdyoosd`  shyyyyyyyyyyyyyyyyyyyhhhhhhmhyyyyyyyyyyyyyyyyyyyyyyydy:::::::::::::::oNNNNNNNMMMMMMMMMM "))
logo.append(list("MMMMMMMNNNNNNNo::::::::::::::::::::::::/sdNNmmmmmhyhms:-/sdho/:-+yddyd/``smdhdhdhhddddddhddhyso+/:::ymyyyyyyyyyyyyyyyyyyyyyyyymy:::::::::::::/mNNNNNNMMMMMMMMMMM "))
logo.append(list("MMMMMMMNNNNNNNm/::::::::::::::::::::::::::/oymNmmmmdyymy:-:-:+ymhsydNmy/+o/::::/:://///::::::::::::::hmyyyyyyyyyyyyyyyyyyyyyyyymy::::::::::::hNNNNNNNMMMMMMMMMMM "))
logo.append(list("MMMMMMMMNNNNNNNd/:::::::::::::::::::::::::::::+sdNNmmmysddsddysymNds/:::::::::::::::::::::::::::::::::hmyyyyyyyyyyyyyyyyyyyyyyyydh/:::::::::sNNNNNNNMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMNNNNNNNh/:::::::::::::::::::::::::::::::/sdNmddhmNshNmho/:::::::::::::::::::::::::::::::::::::ymyyyyyyyyyyyyyyyyyyyyyyyyhm+:::::::oNNNNNNNNMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMNNNNNNNh::::::::::::::::::::::::::::::::::/sdmdMMds+::::::::::::::::::::::::::::::::::::::::::smhyyyyyyyyyyyyyyyyyyyyyyyhmy/::::oNNNNNNNNMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMNNNNNNNh//+osyyyyyyyyso+//+osyyyyso+/::::::/+hdyyyyso+/:::::::::::::::::::::::::::::::::::::::/hdyyyyyyyyyyyyyyhhddddddddNmo+/oNNNNNNNNMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMNNNNNNNNdmNNNNNNNNNNNNNNNNNNNNNNNNNNNho::+ymNNNNNNNNNNNds/::::::::::::::::::::::::::::::::::::::oddyyyyyyyyyhmNNNNNNNNNNNNNNNmNNNNNNNNMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNhyNNNNNNNNNNNNNNNNmo:::::::::::::::::::::::::::::::::::::::oddyyyyyymNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN+:::::::::::::::::::::::::::::::::::::::/smhyyymNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMNNNNNNNNNyyyyyyyymNNNNNNmyyyymNNNNNNNNNNNNNyyyydNNNNNNNh::::::://///:::::::::::::::::::::://+++++omdhhNNNNNNNmyyyyyyyyNNNNNNNNNMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMNNNNNNNd::::::::yNNNNNNs::::yNNNNNNNNNNNNd::::+NNNNNNNm+osyhdmmmmmmdhyso+::::::::::/+syhdmmNNNNNNNNNNNNNNNNNy::::::::dNNNNNNNMMNNNNNNMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMNNNNNNNNNNNm+++/::::yNNNNNNs::::sNNNNNNNNNNNNd::::/NNNNNNNNNNNNNNNNNNNNNNNNNNds+::::/ohmNNNNNNNNNNNNNNNNNNNNNNNNh+++/::::dNNNNNNNNNNNNNNNNNNNNMMMMMM "))
logo.append(list("MMMMMMMMMNNNNNNNNNNNNNNNNNNy::::yNNNNNNs::::sNNNNNNNNNNNNd::::/NNNNNNNNNNNNNNNNNNNNNNNNNNNNmh++ymNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNs::::dNNNNNNNNNNNNNNNNNNNNNNMMMM "))
logo.append(list("MMMMMMMNNNNNNNNNNNNNNNNNNNNh::::yNNNNNNs::::sNNNNNNNNNNNNd::::/NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNNNNNNNmmmmmmmmNNNNNNNNNNNNNNs::::dNNNNNNNNNNNNNNNNNNNNNNMMMM "))
logo.append(list("MMMMMMNNNNNNNNNmhyo+++++++++::::yNNNNNNs::::sNNNNNNNNNNNNd::::/NNNNNNNNNdhyoo+++++++shmNNNNNNNNNNNNNNNdyo+////////+oshdNNNNNNNNNs::::dNNNNNNNNmy++++sNNNNNNNNMMM "))
logo.append(list("MMMMMNNNNNNNNdo/::::::::::::::::yNNNNNNs::::sNNNNNNNNNNNNd::::/NNNNNNNm+/:::::::::::::+hNNNNNNNNNNNNy+/:::::::::::::::/dNNNNNNNNs::::dNNNNNNNh+:::/smNNNNNNNMMMM "))
logo.append(list("MMMMNNNNNNNNs/::::+oyyhhyso/::::yNNNNNNs::::oddddddddddddy::::/NNNNNNNNs:/+osyyhhys/:::/hNNNNNNNNNmo::::/+shhdddhyo::::dNNNNNNNNs::::dNNNNNh+:::/odNNNNNNNNNMMMM "))
logo.append(list("MMMNNNNNNNNo::::+dNNNNNNNNNy::::yNNNNNNs::::::::::::::::::::::/NNNNNNNNNdmNNNNNNNNNd/:::+NNNNNNNNN+::::odNNNNNNNNNh::::dNNNNNNNNs::::dNNNdo/:::+hNNNNNNNNNNMMMMM "))
logo.append(list("MMMNNNNNNNh::::+mNNNNNNNNNNh::::yNNNNNNs:::://////////////::::/NNNNNNNNNNNNNNNNNNNNN/:::/NNNNNNNNy::::+NNNNNNNNNNNd++++mNNNNNNNNs::::dNms/:::+hNNNNNNNNNNMMMMMMM "))
logo.append(list("MMMNNNNNNNo::::yNNNNNNNNNNNh::::yNNNNNNs::::smmmmmmmmmmmmh::::/NNNNNNNNNmhyso+++++oo/:::/NNNNNNNN+::::hNNNNNNNNNNNNNmmNNNNNNNNNNs::::+o/:::/ymNNNNNNNNNMMMMMMMMM "))
logo.append(list("MMNNNNNNNN+::::hNNNNNNNNNNNh::::yNNNNNNs::::sNNNNNNNNNNNNd::::/NNNNNNNdo/:::::::::::::::+NNNNNNNN+::::dNNNNNNNNNNNNNNNNNNNNNNNNNs::::::::::+dNNNNNNNNNNMMMMMMMMM "))
logo.append(list("MMNNNNNNNNo::::yNNNNNNNNNNNh::::yNNNNNNs::::sNNNNNNNNNNNNd::::/NNNNNNd/::::+osyyyyys/:::+NNNNNNNNo::::yNNNNNNNNNNNNNNNNNNNNNNNNNs::::yds/:::/odNNNNNNNNNNNNMMMMM "))
logo.append(list("MMMNNNNNNNy::::+NNNNNNNNNNNo::::sNNNNNNs::::sNNNNNNNNNNNNd::::/NNNNNNo::::yNNNNNNNNm/:::oNNNNNNNNh::::/dNNNNNNNNNNNNNNNNNNNNNNNNs::::dNNdo/:::/smNNNNNNNNNNNNMMM "))
logo.append(list("MMMNNNNNNNm/::::omNNNNNNNms:::::oNNNNNNs::::sNNNNNNNNNNNNd::::/NNNNNN+::::yNNNNNNmh+::::+NNNNNNNNNo::::/ymNNNNNNNNNmdsodNNNNNNNNs::::dNNNNdo/:::/smNNNNNNNNNNNMM "))
logo.append(list("MMMMNNNNNNNh/::::/oyhhhyo/::::::/oosNNNs::::sNNNNNNNNNNNNd::::/NNNNNNy:::::+sssso/::::::/oosNNNNNNNs/::::/+syhhhyso+:::/hNNNNNNNs::::dNNNNNNh+::::/ooodNNNNNNNMM "))
logo.append(list("MMMMNNNNNNNNdo/:::::::::::/oo:::::::mNNs::::yNNNNNNNNNNNNd::::+NNNNNNNh+/:::::::::/oo:::::::NNNNNNNNdo/::::::::::::::/+ymNNNNNNNs::::dNNNNNNNNh+::::::yNNNNNNNMM "))
logo.append(list("MMMMMNNNNNNNNNmys++////+oymNdsssssssNNNdssssdNNNNNNNNNNNNmssssyNNNNNNNNNdyso+++oyhmNmsssssssNNNNNNNNNNmhyo++////++oyhmNNNNNNNNNNdssssmNNNNNNNNNmysssssdNNNNNNNMM "))
logo.append(list("MMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMM "))
logo.append(list("MMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMM "))
logo.append(list("MMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNNNNNNNNNNNNNNNNNNNNNMMMNNNNNNNNNNNNNNMMNNNNNNNNNNNNNNNMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM "))
