
mort = []
mort.append(list("                                                             `             ```       ` `-shdmmmNdmNNNdmNmmNNNNmmNNNNNNNN"))
mort.append(list("                                                             ``            -oo/. `::.+//yhddddmmmmmdmdNNNNNNNNNNNmNNNNNN"))
mort.append(list("                                                             ```       `/. /ddyh/-ddhhddmddhdmmmmNmdmNNNNNNNNNNNNNNNNMNN"))
mort.append(list("                                                             `..```   `+hyssdmmmhymmddmmmmhddNNmNmdmNNNNNNNNNNNNNNNNNMNN"))
mort.append(list("                                               `      `     ```.-+::` .yhddddmmmNNmmmmmNNmhdmNNmNmmNNNNmNNNNNNNNNNmNNNNm"))
mort.append(list("                                             ` ````````````````/sshy/ :dmmmddmmmmmmNNNNmmhdmmNNNNmNNNNNmNNNNNNNNNNNNNMNN"))
mort.append(list("                                       ``....---://+//:-....`` -hdmdhoohdmddmmmmddmNmNNmddmNNNNNNNNNNNNNNNNNNNNNNNNNNNNM"))
mort.append(list("                                    `-:/++:/+//+++++/////:----..-+hmddyhdmmmNmmmNNmNmmmmmdmNNNNNNNNNNNNNNNNNNNNNNNmNNNNN"))
mort.append(list("                                  `:+:/o+y/:+/////://+++++++/:::---:oyhddmmmNNNNNNNmmmNmdmmNNNNNNNNNmmmmmNNNNNNNNNNNNmNN"))
mort.append(list("                                `-:/:/+////:/+///+////::/+++o+++++::::oydmmNNNNNNNNNmNNNmNNNNNNmdmddmmmmmmNNNNNNNNNNNNNN"))
mort.append(list("                              `.://::+/:+:/://+/://///+//:/++oosooo++///smmNNNNNNNmNNNNNNNNNNNNNmmNmNNNNNNNNNNNNNNNNNNNN"))
mort.append(list("                             .-//:::+/:/://+/+/+///:///+oo+/+oooyhhsosoo+sydmNNNNNNNNNNNNNNNNNNNmmNNNNNNNNNNNNNNMMMNMNNM"))
mort.append(list("``                          .-::::::+//++///so+++/////++/osyo+sysyhmdyysyysdmmmNmdmmmmNmNNNNNNmdmNNNNNNNNNNNNNNNNMNMMMMM"))
mort.append(list(":-.`                       .-:/:/://++//s+//+so+o+/+o+/+o++shyoyhhhdmmddyhyshdmmmmmmNNNNNNNNNdmNNNNNNNNNNNNNNNNNMMMMMMNN"))
mort.append(list("-..`                      `-+/:+//+/++o:so++oosssso++ssoossoshhhhddhmmmmdyhyyhmmmmNNNNNNNNNNmmNNNNNNNNNNNNNNNNNMMNNNNmmm"))
mort.append(list("-:-.`                     -:+:++//oo++o+/yo+ooossssoooshyyhysshddddddmmmmdhhhydmdmmmmNNNmNNNNmNmNNNNNNNNNNNMMMMMMNNNmmmN"))
mort.append(list("----::`                  `-/+:++//ososooooyo+oosss++ossshhhddhyhhmmmddmmmmhhhdhdmNNNNNNNmmmNMNNNNNNNNNNMMNNNNNNmmmNNmmmm"))
mort.append(list(":..--:-.`                `-++:/+o/+sssysssyys+sssys++oyyshdddddhdddmNNmdddddhddhdmmNNNNNNmNNNMNNNNNNMMMNNmmNmmmmmNmddmmm"))
mort.append(list("/://:-::-.               .:++///s++sysyhyyyyhsossyssoosyhhyhdmmmddddddmNmmddhyhhyhmNNNNNNNNNNMNMMNNNmmmmNNmmmmmmdmmmmdhd"))
mort.append(list("//-.`.--```              .-++/+++sooyysyhhhhhhysssyyyyyhhhdhhhdmmmddddhhddddhyysyydmNNMMMMNNNMMMmddmmmmmmmmmNdddmdddmmmm"))
mort.append(list(":/::///:-.```            `:/o+oosssyyyyysysssyyhhddhhhhhddhhhhyyhhdddmddhhyhhhys++sdmmNNNNNmmNmmdmmmdmmddmmddNNNmmmmmmmm"))
mort.append(list("-//://:-.``` `           `:/oyssyyyddhhhhyssoso+o+++oosssoooossyhhdmmNmmmmddhhhyo+ohmNNNNNddmmmmddmNdddddmNNNNmNNNmmmmmd"))
mort.append(list("::///:`..`.````          `-++syysyyydhshdy+/////+oshdmddhyso+/+ohNNNNNmmmmNNNmdhhdmmNNMmmmNNmmmdmmNNddmmmddNNmmmmmmmdmNN"))
mort.append(list("---//:`.```.`````   `````.-+ssyyhhsyyhhhyys+//+oshdddhyhhso+:::/odmmmdhhhhhNNmdhsyhmNNmmdmNNddddddddmmhhhhdmmmmmmmmdmmNN"))
mort.append(list(":-.://:.``.-.-..````...---:oshhyhhyyhhddddhy+/:::://+osso+/:----:oyyyyssooohNmhsoooyddmmmNNmNMNmdhhdddmmmmmdmmddddmNNmdh"))
mort.append(list("-/////:----:::::---...---//+sdmdhdhmddmmmmds/:------::::-----....:+soo+////omdysooydmmmmmddmmNmddmNNmmmmmddddhdmmmmNmmmm"))
mort.append(list("-:-::/:::::::///::-------://smmdddhdmmNmmddh+:-.......--:------...-/oo+////+dhyyhddmdmmmmdmmmmdmNNmddmmhhmmmmdhhhdmNNNdh"))
mort.append(list("---::/+//////////::----::::/ohmmddmmmNNNmhhyo/--......-:://:-.-...--/oso+ooshhhyhdmddmdmmdhdddddmNmmmmmmmmmmmmdmmmddmNmm"))
mort.append(list("--:::/+++////+////:::::::/+/osdmmmdmmmmmmddyo/:------::/+///:/++++osyossssyhyyhdmmmmmmmdmmdmNNNNNdhhhdhdNNNmhdddddddmNNN"))
mort.append(list("-:::///++++ooo+/////://+ooooshhhmNNNmmdddhyso//::::::/++/:::/+ooyhyyo+ooooddhyhddhdmmmdmmmdmmmNmmddmmNNmmmddhdmmNNNmmmmm"))
mort.append(list("::::///+oo+sso+++++ooosssyshddhydmNNmmmdhso+//////:////::::-::/+osssyyyo+smmhhhddddmmdddmmmmmmNdhhhhhmNmNNNNmmmmmmmdmmmm"))
mort.append(list("o:::////ooooysooosssyyyyyyhmmmyhmmNNNmmmdy+/::://::::://sssssyyyhhhhhso+smNNdhmdddhddmddmmmNNNNmdddmmNmmmmdmmmmmmmdddddd"))
mort.append(list("h+//////+oooyyssyyyhhhhhhhhdmmdmmdmNNNmNNys+/:::/:::::///::///+ossshhsosmMMNNmmmdmddmddddmdddddddmmddmddddddddhhhhhhhhhh"))
mort.append(list("ds/////+++o++oosyhhhhdddddddmNNmNNNNNNNNMmoo+////:::::/:::://+osyhhysosmMMMNNNNmmNNNNdmhdmdddddddhhhhhhhhhyyyyhhhhhyhhyy"))
mort.append(list("dh/////:::///ooosyhdddmdmmmmmNMNNMMNNNmNNMh+oo+////:::::::::::://+///+dMMMNNNmmmmmmNNmmddNdddhyyyyyyyyyyyyyyyyyssssssoss"))
mort.append(list("dh+:-``.:/::///+syyyhhyymmNmmmNMNMMMNmmNNMNo+osyyo+++/:::------/++/+odMMMMNNNNNmmmmNNmmdmNmdmdhssyyyssssssssssoooooooooo"))
mort.append(list("soo-.-.-:/+ooooo+++oyho+mNNNmmNNMNNMMmmNNNMNy/--..-://::/+o+://++oosdMMMMMMMNNNmmmmddmmmNmNdmmhdsooooooooooooooo+++ooooo"))
mort.append(list("o+//::---ohhhhhdydhhhmhyhNNNmNNMMNNNMMmmNNNNm-.`````......-..-:/:...:dMMMMMMMMNNmmdmmddNNmNdNdhmho++++++++++++++++++++o+"))
mort.append(list("-------:/+syysooooooossshmNNNMmMMMNNMMMNNmmNd..`````..``````````...:ymMMMMMMMMMNNNmmmmddNNNmNmdmNh++++++++++++++++++o+++"))
mort.append(list("------:::::::::::::/oysddmNNNMNNMMMNNNNNMMMMMs:------:--..--....--:/hMMMMMMMMMMMNmmmmmdNNNNNmddmNNd+++++++++++++++++++++"))
mort.append(list("........--....--/shhddhdmNNNNMMNNNMMNmNNNMMMMMo:---::::::::::::::///yMMMMMMMMMMMMNNNNmdMNNNmmmmNNNNmh+/+//+/++++++++++++"))
mort.append(list("...........---:ydhhhhddmmmdNNmmmNMMMMNNNNNMMMMNo:----::::::-::::+++ooNMMMMMMMMNNNNNNNMMNmmmmmNmmmmmmmmdo+//+++++++++++++"))
mort.append(list("......----::/shddhyhdddmmdNNmNNNMMMMMNmNNNNMMMMMmo::::::::::::///++++yMMMMMNNNMMMNNNNmdsmddmmmmdddmmmNNmds+////+++++/+++"))
mort.append(list("-----------shhhyhmmmmmNNNMNmNmNNMMMMMNNmmmNMMMMMMMd+::::/:/:////////+sMMMMMMMMNNNNmmmhyomdmmmmmdmmmmmmNNNms++/++++++++o+"))
mort.append(list("---------:hhhyyyyyydmmmmNNNNmmdNNMMMMNmddmmNMMMMMMMNy::://///++++/++osmMMMNNNNNNNNNNNmmmNNmmmmmNNNmmdmmNNdo+++++++o++ooo"))
mort.append(list("......-.-hdhyyyyyyhdhdmmNNNNNNNNNNNNNNNmmmmmmNMMMMMMMd/:://+++++++osyyNMMMNNNmmmmmNNNMMMMNNNNNmNNmmmmNNNNmdy+/++++++/+++"))
mort.append(list(".......-ydhhhhhhhddmNNmmmNNNNMMMMMMMMMMNNmmmNNNMMMMMMMo-::////://+osyhMMMMNNmNNMMMMMMMMMMMNNmNdmddmmNmdNmmddms++++++++++"))
mort.append(list(".------smddmdhhddhdddmmNNNNNNMMMMMMMMMMMMNmmmmNNMMMMMMy---::--:::/+oymMMMMMMMMMMMMMMMMMMMMNNmNmNNNNNmmmmNmdhmNyo++oooooo"))
mort.append(list("---:-:/NNNddmmdhdddddddmmNNNNNMMMMMMMMMMMMNmNNNMMMMMMMy..--...---:/ohMMMMMMMMMMMMMMMMMMMMNNNMMMMMMMMNmmmMmhhdNNhoooooooo"))


ninja = []
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMhh////+ysshmmmmNNNNNNNNNmddmmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMNNNMMMNMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMdh/////ysshmmmNNNNNmddhhhhhhhhNMMMMMMMMNNmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMNNNMMMNMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMmh+////ysshmmNNNmdhhhhhhhhddddNMMMMMMNNmhos+--odNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMNys////sssymNNmhhhhhhhhhhhdhdmNNMMMMMMMMMNNNhy+dmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMyy////sssymNddddhhhhhhhhhhhmNNMMMMMMMMMMMMNmyoNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMyy////osssmmmNNdhhhhhhdhhhdmMNMMMMMMMMMNNNmh+hNMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMhh////osssmNNNNdhhhhhmdhhhmNMMMMMMMMMMMNMNyo-hmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMdh////+ysshddhhddddhdmmdddmMNMMMMMMMMMMNMNs+:dmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMmy+////yssyhhhddhhhhdddmmmmMNMMMMMMMMMMNNNo:omNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMNys////yssyhhdhddhhddddNmmmdmNNNMMMMMMMMNms-ydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMyy////sssymdhhhhhhddNNNNMmssdhdMNNMMMMMNdy/hmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMhy////sssyNmdhhdddddmdmmmMNMMMMMMMMMMMMmh/+dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMdh////ossyNNmmdddhddmNNNMMMMMMmNNhdmhdmhyodmNMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMmh////oyssmNNNmmmddmNMMMMMMMMMmmmhhhyyyyyyssyyhdmNNNNMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMMMMMNMMMMMMMMMMMMMMMMMMN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMNy+///+yssdmmmNmmNNNNNNNMMMMMMmddddssyysosssoossyhddsydNMMMMMMMMMMMMMNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMNN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMys////yssyhhhdmNNNNNNMMMMmmNNNdhhhoyyyysooooossyhdhsdNMMMMMMMMMMMMNMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMyy////yssyhhddmmNNNMMMMMmdddmNmhhddyysso++++oosyhdyydNMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMhy////syyyhhdddmmmmmNNmmddhdmMNdhmhhyssoo+oooosyhdyyhmhdmMMMMMMMMMMMMMMMNMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMdh////syyyhdddddhhhhhhhdhddddmNdyhhyyooooooosssyhhyyhdmmdssyyydddddmNNMMNMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMmh+///+yyydddddhhhhhdddddddhhdmmddhysoooooosssyhyysyyhmmm+:-:::::///++ossydNMMMMMMMMMNMMMMNMMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMNyo//ysyyyhhhhhhhhhhhhhysooosooommhyossooosyyhhysssyyhddd+:-:-:--:::::::///+sdNMMMMMMMMMMMMNMMMMMMMMMMMMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMys/++yyyyhhhhdhhddds+++///++///omdhyyyyyhhhyyyyysssyyhhh+:---:::/::+/::+////+sNMMMMMMMMMMMMMMMMMMMNNNNNmmN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMyy/+/sdyyhddddddds+:://::///////+hddmmmmdyyyyyyyssyyyhyh//-----/oo+s+/oo/::///omMMMMMMMMMMMMMMMMMNMMMNMMMM"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMhy+//-dhydmmmmmy+:://:::::/::::::/++hdhhhdhhyyyyyyyyyyyy/:---:::/ooo/oyyo+/:::/sNMNMMMMMMNMMMMMMNMMMMMNMNN"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMdy+/+-oyydNNmh+::::/://::::::::::///ohdhhhhhhhyyyyyyyyy+/--/+/:++ohysooo//:-/::/yNMNMMMMMMMMMMMMMMMMMmdddd"))
ninja.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmh++++syshdy+///:://:+o+//://://+oo//syyhhyyhhhhyyyyso+/:-/oo//ssshhyo+///::/-::+hMNMMMMMMMMMMMMMMMMMmhhhd"))
ninja.append(list("MMNNNNMMNNNNNNNMMMMMMMMMMMMMMNyo+o+o+++o+/:/-/://:/+o+//+++oosss//+syyyyysssyyyso++:::+ssyyyhhyhhsoo++:::/-:-/omMMMMMMMMMMMMMMMMMMMdhhh"))
ninja.append(list("NNNNNNNNNNNNNNNNMMMMMMMMMMMMNhoo++/++o+/os::::////:/+o+//++oossso/+oosysssooyy+//++o/+hyyyyhhhhhhyyyso:::/::-//sMMMMMMMMMMMMMMMMMMMNhhh"))
ninja.append(list("NNNNNNNNNNNNNNNNMMMNNNNNNMMMNsooooo++oy+os::::://+///+oo+++oosyssooooooosssys+/oossyssyhos+hhhhhhdmNmmyso/:--///dMMMMMMMMMMMMMMMMMMMdyh"))
ninja.append(list("NNNNNNNNNNNNNNNNNNNNNNNMMMMMho+++oooosyyys:://://++//+oso+ooooossssso+///++ooydmmdhyyhshysyhhhhhhdNNNNNMMmhs+//:+mNMMMMMMMMMMMMMMMMMdhd"))
ninja.append(list("mNmmmmmmNNNNNNNNNNmmmmmNMMMNhysoososssy+++////+///o+/+ooss+++++oo+++os++/ohmNNNNdhydhyyyyhhhhhhdmNNNNNMMMMMMMds//smmNNMMMMMMMMMMMMMNhhd"))
ninja.append(list("mmmmmmmNNNNNNNmmmmmmmmdNmmdmmho+oooossss//////+++/+o+++o+ossoooso+//+++sdNMNNNNmdhhhyyysyyhhhhhdNNNNNNMMMMMMMMMhydddmmmmNNMMMMMMMMMdhdm"))
ninja.append(list("mmNmmmmmmmmmmmmmdddmmmmmdddmmmdysssssyyy+++++/+++ooo+//++osyysyyso++/odMMMMNNNNdhhyyyyyyyyyyyyymNMMMMMMMMMMMMMMMy//odddmmmmNNNMMMNdhmNN"))
ninja.append(list("NNNmmmmmmmmmmmmmmmmmmmmmmmmmmddmhdddmmdsosyyyhhhyyhys+////++ososoo+/oNNMNNNNNNNNmdhhyyyyyyssyymMMMMMMMNNNMMMMMMM+-:+dNmddddmmmmdddmNMMM"))
ninja.append(list("NmmmmmmmmdmmmmmmddmmmmNNmmmmmmmNNNmNNmhdmmmNMMMMMMMNmy+////++osossosmNMNNNNNNNNNNMNdhhhhhyssshMMMMNNNNNNNNMMMMMm/+yNMMNNNNNmmmmNNMMMMMM"))
ninja.append(list("mmmmmmmmddddddmddddddmNNNmmmmmmNNNdmmNMNNNNNNNNNNNNNNNs+////++oossssNMMMNNNNNNNNNNNdhhhhmmhhdmNNNNNNNNNNMMMMMMNddNMMMMMMMNNNNMMMMMMMMNN"))
ninja.append(list("mmmmmmmdddddddddddddddNNNmmmmmmNNNNmmNMNmNNNNNNNNNNNNNNy++//+/++oossmMMMMMNNNNNNNNNNmmmmmdhhyyhdmmmmNNNMMMMMMNmdmNNMMMMMMMMNNNNMMMMMMMM"))
ninja.append(list("mmmmmmmmmmdddddddddhhdmNNmmmNNNNNdyodmNNmmmNNNNmmmNNNNNNy++//+++++ooyNMMMMMMMNNNNNmmhdddhys++/+/oydmNNNNNNMMmhyhdmNNNNNMMMMMMNNNNNNNMMM"))
ninja.append(list("mmmmmmmmmmdddddddddhhhhdmmmmmmmmdsooyNNNmmmmmmmmmmmmmmNNNho+////++ooosdNMMMMMMMMMMMNNmmho/. .:///oyhmNNMNmdhhhhhhdmNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("mddmmddddddddddddddhhhhhhhdmmmmddsooohmmdydmmmmmmmmmmmmmmNdo////+++ooooydNNMMMNMMNNNmmdyo+/-/++yhmNMNmmdmmdhhhhhhddNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("ddddmddddddddddddddhhhyyyyhdmmmdhyoooysssyssshhmmmmmmmmmmmmdo+//////++syyshhdmNNNMNNMMMNNMMMMMMNNNNNmmddddhhhhhhhdmmNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("ddddddddddddddddddddhhhyyyyhmNNNNmmmmmNNNmyhdddmddmmmmmmmmmdys+/////+++osssssyyhyhhmmNmNmmNdmdysssdNNNNmmddddddddmmNNNNNNNNNNNNNNNNNNNN"))
ninja.append(list("ddddhdddddddddhdddddhysoooooossyhdmMMMMMMMMMMMMNNNmmmmmmNMMMNmyso+++ooooossssss+osydhddhyhyso+sssooymNNNNNmmmmmmmmNNmmNNNNNNNNNNNNNNNNN"))
ninja.append(list("dddhdhdddddddddhhdhyo++//+++++ooossydMMMMMMMMMMMMMMMMMMMMMMMMMMNhyooso+++osoo++so++o+ssssyssoooo+osyydNNNNNNNNNNNNNNmmmmmmmmmmmmmmNNNNN"))
ninja.append(list("ddhhhhhhddhhddhdhyso+//////+++++++oooyNNNMMMMMMMMMMMMMMMMMMMMMMMMMNdhysssssssyyyyysysoso++++syhhdmMdhhmNNMNNNNNNNNNNmmmmmmmmmmmmmmmmmNN"))


skurk = []
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNNNMNMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMNNNmmmmNNNNNNNNNMMMNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmddhhhyyyyyhddmmmmNNMNNNMNMNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhyssoo++++++++oyssyhdmNNNMMMMMMNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmmdhysoooo++//::::::::///+++sydmNNMMMMMNNMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNNNNNmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMNNmmNmdysooooo++///::-----:::://+++osyhmNMMMNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNmNNmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMNNmNNNmhysso+//::::-----------::/++oosooymNNNNNNNNNNNMmmmNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNNM"))
skurk.append(list("MMMMMNmNNmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMNNmNMNmhyso+/:::-----....-----::://++ossshmNNNMMMMMMMMmdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmN"))
skurk.append(list("MMMMMNmmmmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMNNMMNdhso+//:::----.......-----:://++ossydmmNMMMMMMMMdhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNm"))
skurk.append(list("MMMMMNmmmmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMNmyo+/::--......```````.....--::/+syhhmmNMMMMMMMMhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm"))
skurk.append(list("MMMMMNmmmmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMNmyo+++/:-...`````````````.-:////+symdNmNMMMMMMMMysNMMMMMMMMMMMMMMMMMMMNNNmhshmdmdmNMMMMMN"))
skurk.append(list("MMMMMNmmmmmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMNmmhso+////:-.```````````.--:::/+++sydmNNNMMMMMMMMyoNMMMMMMMMMMMMMMMMMMNNmdhyohmmmhmNMMMMMM"))
skurk.append(list("MMMMMNmmmmmmNNNNNNMMMMNNNNNNNNNNNNMMMMMMMMMMNmmy+:-..--:/:-..``````.----.....-/shhmmMNMMMMMMMMyoNMMMMMMMMMMMMMMMMMMNMMMMMMNMMMMMMMMMMMM"))
skurk.append(list("MMMMMNmmmmmmmNNNNNMMNNNNNNNNNNNNNMMMMMMMMMMMNNh+:::::::://::-.```..--::::::---:/yhdmNMMMMMMMMMysNMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNmmmmmmmNNNNNMMMNNNmmmmNNNNMMMMMMMMMMMMNmo//oo+sso--:/+/-...-::::-:+o+/+/::+hhdNMMMMMMMMMhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMNmmmmmmmNNNNNMMMNNmmmmmmNNNNNNMMMMMMMMNmy+/oo+/sys-.-:++:---:/:--./yyo:+o/:/yyydMMMMMMMMMdhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMmmmmmdmNNNNNMNNNNNNNmmmmNNNNNMMMMMMMMNms+/++/::----:/+//:::://:-----::://:/oy+hMMMMMMMMMmdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
skurk.append(list("MMMMMMmmmmmdmNNNNNMMMMMMMMMMNNMMMMNMMMMMMNNmms+//::::---:+o+/::--:///:::::-:::://oo:oMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmddmMM"))
skurk.append(list("MMMMMMmmmmmdmNNNNNMMMMMMMMMMNNMMNNMMMMMMMNNNmy+/:::----:+o++/::-::/://-----:::///o++yMMMMMMMMMNmMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdyo++hmNMN"))
skurk.append(list("MMMMMMmmNNmmmNNNNNMMMMMMMMMMNNNNNMMMMMMMMMdNmyo/:--....:/oso/:-:://///-....---://o+sNMMMMMMMMMNNMMMMMMMMMMMMMMMNNmdhhhhyyso+++:/:/ymMNN"))
skurk.append(list("MMMMMMmmNNmmmNNNNNMMMMMMMMMMNNNMMMMMMMMMMMmmNho/:--....-+ss+:-..-:/++/-......--:/o+dMMMMMMMMMMNNMMMMMMMMMMNmhssoo+//:::::::://:::/omNNm"))
skurk.append(list("MMMMMMNmNNmmmNNNNNMMMMMMMMMMNNMMMMMMMMMMMMMNNdo/:--...-/soo/:-..--://+:......--:/sdNMMMMMMMMMMNNMMMMMMNdyo+/::::::::---:::::::::::/hmNm"))
skurk.append(list("MMMMMMNmNNNmmNNNNNMMMMMMMMMMNNMMMMMMMMMMMMMMMms+:-----:/ooooo/::://///:-------:/+dMMMMMMMMMMMMNNMMMMmy+/:----------------::::::::::+hNm"))
skurk.append(list("MMMMMMNmNNNmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMNho/:::::/+//////+/::::://::::::::/sNMMMMMMMMMMMMNMMMMho/:--...------::://:///++/::::::+hN"))
skurk.append(list("MMMMMMNmNNNmmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMms/:::/+oo+/:--..-..-:://+/:::::/omMMMMMMMMMMMMMMMMNy+/:-.......----oysoooooooss+::::::+h"))
skurk.append(list("MMMMMMMNNNNmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdo:--/+shy++///:::://+oso+/:-:/+hMMMMMMMMMMMMMMMMNy+/::-.......---:osooooooooooo/::::::+"))
skurk.append(list("MMMMMMMNNNNNmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho:-:/+sy+/::.--.--::+s+/:--:oyMMMMMMMMMMMMMMMMNy/+:-::.......--/syysoooooooosso/:::::/"))
skurk.append(list("MMMMMMMNNNNNmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+::/osso++::/::-/++ss+::-:ohNMMMMMMMMMMMMMMMMh:+/--::.......-+yyyyysoooooooosso/::///"))
skurk.append(list("MMMMMMMNNNNNmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMNNh+:/+yyoo+//:::/+oos+/:-:ohMMMMMMMMMMMMMMMMMm+-+:-.::-....--/syyyyyysooooososssy+////"))
skurk.append(list("MMMMMMMNNMMNmNNNNNMMMMMMMMMMMNMMMMMMMMMMMMMMMMMNmmmy+:+ossoo+::::/+o+//:-/oyNMMMMMMMMMMMMMMMMNy::/:-.::---.--:ssyyyyyyyysoossssymMmo//+"))
skurk.append(list("MMMMMMMNNMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNddmmho/++++//////:::/:::/symMMMMMMMMMMMMMMMMNys--/:--::-----:oyyyyyyyhhhyssssydNNNMNo++"))
skurk.append(list("MMMMMMMMNMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhdmho++//::-----::::/+ssyNMMMMMMMMMMMMMMMMhoo--+---:/-----:shhyysyhhhhhhyshNMMMNNMNs+"))
skurk.append(list("MMMMMMMMNMMMNNNMNMMMMMMMMMMMMNMMMMMMMMMMMMNNmNmmdhysyddyo+/::-----:::/ossshdmmmNNNMMMMMMMMMdoos--/:--:+:--::-:yyyyyyhhhhhhydMMMMMMMNNNh"))
skurk.append(list("MMMMMMMMNMMMNNNMMMMNMMMMNNNNNMMMMMMMNNmmddhddNmmdhyssosddyo++/////++oooosshdddhhhhhdmmNNMMN+++y:-:/---+/:-:/::syhhyyyhhhhyssdMMMMMMNNNM"))
skurk.append(list("MMMMMMMMNMMMNNNMMMMNMMMMNNMMNNNNmmmddhhyyyhddmdddhyssoo+ossssysssoo++++osyhdhhhhyyyyyhhhdmdyyyhs+/o/:-/o/:://+hhhhhhhyhyssssshNMMMNMMMM"))
skurk.append(list("MMMMMMMMNNMNNNNMMMMNNMMNNNNNNNmmmdddhhyyyhhhddddhyyssoo++///////////+++ossyhhhhhyyyyyhhhddmmmdddddddhyyhyo+ooosdddhhhyssssyyyyhmNNMMMMM"))
skurk.append(list("MMMMMMMMNNNNNNNNNNNNNNNNmmmmmmmmmmmdddhhhhhhdhdhssssssoo++//////////++ossoshyyhhhhhhddddddddhhhhhhhhhhdddddhhsoohddhyyyssyyyyyyydMMMMMM"))
skurk.append(list("MMMMMMMMMMMMMNNNNNNNNmmmmddmdddmddddddmddddddhyhsoosssoo++++///////++oooo+yyyyhhhhhhhhhhhhhhhhyyyyyyyyyhhhdddmdyohyyyyyyyyyyyyyyhdNMMMM"))
skurk.append(list("MMMMMMMMMMMNNNNNmmmmmdddddddddddddddddddddddhhyyhsossssoo++++++///++ooooosysyyhhhhhhhhhhhhhhhhhyyyyssyyyyhhhhdddmmdhhhhhhhyyhhhhhhdNMMM"))
skurk.append(list("MMMMMMMMMMNNNNmmmmmddddddddddddddddddddhhhhhhhyyyhsssssoo++++++++++oosooshyyyyyhyhhhhhhhhhhhhhhhyyyyyyyyyyyyhhhddmmmhhhhhhhhhhhdddddmNh"))
skurk.append(list("MMMMMMMMMNNNNmmmmmddddddddddddddddddddddhhhhhhhhhhdyyyssooo+++++++oosssshhyyyyyyyhhhhhhhhhhhhhhyyyyyyyyyyyyyyhhhddmmmmhdddddddddddmmMMd"))

hagge = []
hagge.append(list("mmmmmdmmdmdmNNNNNmNNNNMNdmddmhdhsh+/yodhymhdh+ssdMMNmdo/.-:::::::"))
hagge.append(list("mmmmddddddddmNNNNNNNNNNMNdNmdmdddyho+yodhydhdhoysdMMNmho/.-::::::"))
hagge.append(list("mmmmdmmdmddmmNNNNNNNNmmmhsyyyyoooo++/soosshddmdhdNMMNdho:.-::::::"))
hagge.append(list("mmmmdmmdmddmmNNNNNmhyoo+o+oo+++++///::::/:/+osyshNNNmsoo/.-::::::"))
hagge.append(list("mmmmdmmdmddmmmmmdhysoooo+////+++++/::::/::::::/+sdmmmyys:........"))
hagge.append(list("mmmmdmmdmddmmdysyhdysoosoooo++++////+/+++//++++//+shhyys:.://////"))
hagge.append(list("mdmmdmmdmdddsssyoosssysssssysso+++++///+ooo++osyyo+oooso:.::////:"))
hagge.append(list("mdmmdmmddyyyosdhyo++ooosssssooooooo++++o+++ooosssss+///+:.::::///"))
hagge.append(list("mdmddmdhsyso+oshdhyyysosssssssoo+++oooo++oo+osssso+oo++o+/:/:////"))
hagge.append(list("mdmdhho+oyys+ososssyyyyssooo+++++++++++oossyysyyyyyooosos+/::::::"))
hagge.append(list("mdmds//+sysyooooooooo++++oo++///////+oossssyyyyhhhhhsossoo--....."))
hagge.append(list("mddy+/++sssyyyyyyyhhyyysoooo++////+/+++osyhhyysssyhhdhssso..`````"))
hagge.append(list("ddhoo/+oo+oosyyhyhhhyyyysyyyyyyyhhysoo++oosyyyyhhyhdddhsss:.`````"))
hagge.append(list("dddy+/////+ssyyyyyyssssyyhhdddddmmmmdhyo+++osyhhhhdhdhssss/.`````"))
hagge.append(list("ddhs/://///oooyyyyyysssssssyyyhhhdddmmdhs+//oyyhhhhhyyo+oo+:-----"))
hagge.append(list("mmhs/://++/+o/+oosssyyyyssooosssyyyhhdddhys+//oyhyyysss+o+osyysss"))
hagge.append(list("mNdss/++so/+++++++ssoossssoo++ooosssyyhhhhyyso+ooyysooss+oosyhhys"))
hagge.append(list("mNmdho+ysy++o++ooo+sssoooooo+++ooooosssyyyyyyssssyyssoyyoooyyhhyo"))
hagge.append(list("NMNNhhsyys++++++ooooosoooooo+++++++ooooosssssssyyydhyyyhysohhhhho"))
hagge.append(list("MMMNmdhshh+++++oooooooooooooooooo++++++ooooooooshdddhhdhhhsyyyyy+"))
hagge.append(list("MMMMNddddd+++ossyssyssssosyssssssssssoooo+++++/+ohddhhddhhyssooo/"))
hagge.append(list("MMMMNyhddd/osyhhhddddhhyssssshhddddhhyysssso+////shdhsyhhyhhyyyy+"))
hagge.append(list("MMMMNhhhdh++shddmdmNNNNmy+//oyhdmhdmmddhhyyo//::/oyhhyssyyyo++os/"))
hagge.append(list("NNNNNNhhyh+/++osyyhhddddo:::+ssyyhyyyoo++//:::::/+syhysysy/......"))
hagge.append(list("MNNNmNMdyho/:://+ossssso:::://+++ooo+//:::---:://+oyyysosy:----.."))
hagge.append(list("NNNmmNNNmmy+/////////++/:::::::::::///::::::::////so/o+oss/::::-."))
hagge.append(list("NNNmmmNNNmmo///::://+++:::::::////:::::::::///////////+++o/::::--"))
hagge.append(list("MNNmmmNNNNmy+++///++ss/:::--:::/o+//::::////////////+ydhhho::::--"))
hagge.append(list("NNNmmmmNNMMNooo+ooosysssoo+oso/+ooo+//////+///////hNNNmNNMN/:/osy"))
hagge.append(list("NNNmmmmNMMMMyosossssoosyhhyhhhy+//++++///+++/////+hMMNNMMMNddmmmm"))
hagge.append(list("NNNmmmNMMMMMmoosssooo+oosyysoo+/////+++++++///////hNMMNNMNNMMMMNN"))
hagge.append(list("NNNmmNMMMMMMNyoooooyysyhhhyyhysooosoo++++////++++/dNNNMMMMMMMMMMM"))
hagge.append(list("NNmNNMMMMMNMMNoooosssssyyyyyysssooosso+/////+++++/mNNNNNNMMMMMMMM"))
hagge.append(list("NmmNMMMNMMMMMMdoooso+oosyyhhyyso++//+o++++++oooo/+NNNNNNNNNMMMMMM"))
hagge.append(list("mmNNNNMMMMMMMMNdsssoooooooosoo++++++++++oooosso//hNNNNNNNNNNMMMMM"))
hagge.append(list("mNNNMMMMMMMMMMMNhossoo+//////::::///++oosssss+//sNNNNNNNNNNNNMMMM"))
hagge.append(list("NNNMMMMMMMMMMNhhy+ossoo+ooooo++/++++ossyysso+/+omNNNNNNNNNNNNNMMM"))
hagge.append(list("NMMMMMMMMMMMm+ohy++oyhhhhhhyyyyyhyyhhhyyso++++odNNNNNNNNNNNNNNNMM"))
hagge.append(list("MNMMMMMMMMMm/+sdy+++ooydmmdddmmmmmddhysoo++++oyNNNNNNNNNNNNNNNNNM"))
hagge.append(list("MMMMMMMMMMN//+ymyo+++oossyyhddddhhyyssooo+++osmMNNNNNNNNNNMMMNNNN"))
hagge.append(list("MMMMMMMMMMy-/+hdys++++oossssyyysssssoo++++++shNNNNNNNNNNNMMMMNNNN"))
hagge.append(list("MMMMMMMMMN:::/hdysoo++ooossssssssoooo+++++ooomMNNNNNNNNNMMMMMNNNN"))
hagge.append(list("MMMMMMMMMh.-:/hhysoo+++ooooooooooooo+++++oo+sMMMMMNNMMMNNMMMNNNNN"))
hagge.append(list("MMMMMMMMN:.--/yyso++///+++ooooooo+++++++++:/NMMNNMMMMNNMMMMMNNNNN"))
hagge.append(list("MMMMMMMMs`---:ss++//:://++++++++++///////-:dMMNNNNNNNNNNMMNMMMNNN"))
hagge.append(list("MMMMMMMd.`.-.-+o+///:::////////////////:..sMMMNNNNNNNNNNNNNNNMMMN"))
hagge.append(list("MMMMMMN:``....-o+///:::::::::::::/::/:-`.+mMNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("MMMMMMN::-...`./++//::::::::::::::::-```:yMNNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("NNMMMMMms+-````-++//::::--------:::. -oo+NNNNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("NNNMMMMNMo/:--.`.//:::-----------.``-ossmNNNNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("NNNNNNNNN/:+++/-.-::::---------..:/+++ymNNNNNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("NmNNNNNNN:-://+/-```.--------.`.:///omNMMMMMNNNNNNNNNNNNNNNNNNNNN"))
hagge.append(list("mmNNNNNNN-`..---:::.``-:---.``.-:-+mNMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))

logo = []
logo.append(list("MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNmNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
logo.append(list("MMMMMMMMMMMMMMMMMMMMMNNmmmmmmmmddddddmmmmmmmmNNNMMMMMMMMMMMMMMMMMMMMMM"))
logo.append(list("MMMMMMMMMMMMMMMMMNNmmmmdhyso+//////////++osydmmmmmNMMMMMMMMMMMMMMMMMMM"))
logo.append(list("MMMMMMMMMMMMMMNNmmmdyo+///////////////////////oshmmmmNMMMMMMMMMMMMMMMM"))
logo.append(list("MMMMMMMMMMMMNmmmdy+///////////////////+++o++/////+shmmmNMMMMMMMMMMMMMM"))
logo.append(list("MMMMMMMMMMNmmmho///////////////////ossssssssssss+///+ymmmmMMMMMMMMMMMM"))
logo.append(list("MMMMMMMMNmmmho////////////////////ohysssssssssssy+/////ymmmNMMMMMMMMMM"))
logo.append(list("MMMMMMMNmmds//////////////////////ysssssssssssssy///////+hmmmMMMMMMMMM"))
logo.append(list("MMMMMMmmmh////////////////////////ssssyssssssssso/////////smmmNMMMMMMM"))
logo.append(list("MMMMMmmmy/////////+o+///+oo+///////yss/sssssssssss+////////odmmNMMMMMM"))
logo.append(list("MMMMmmmy///////oo+:````````:+ho////ys/yyssssssssssss+///////+dmmNMMMMM"))
logo.append(list("MMMmmmh/////o+/.`````````:oyh:s///////+ossssssssssssso///////ommmMMMMM"))
logo.append(list("MMNmmd//+sy+`````````.+shyyh-`:o/////+`.ysssssyssssssh////////ymmmMMMM"))
logo.append(list("MMmmmsoo/--/+///:.:oyhyhddmd+``y/////++.sssoo++ossyssh/////////dmmNMMM"))
logo.append(list("MMmmmo:---------:ydyhddddmmmd::s+//++odoso+++sso++ohyo/////////ymmNMMM"))
logo.append(list("MNmmdo:----------:hhdmmmmmmmm+/ooo+++++o++osys+o+oso///////////ommmMMM"))
logo.append(list("MNmmhdhs/---------ysmmmmmmmmmo.`yoooo+oo+yhsosyyyh/+/+/////////+mmmMMM"))
logo.append(list("MNmms+dhhy+-------+yhmmmmmdy+:/:os//////+soo+--/++.`:s+/////////mmmMMM"))
logo.append(list("MNmmy/sdhhhhs:-----hsmmhs+:--:+sooso////////:.:+::.`:o/////////+mmmMMM"))
logo.append(list("MNmmd//+sddhhhy/---ss+:://:--yms+:-/so////+ssyyyyyysyy/////////smmmMMM"))
logo.append(list("MMmmm+////oyddhhho:/d-/s/:..``//+.```o/yyyyyyyyyyyyyyh+////////hmmNMMM"))
logo.append(list("MMNmmy///////oydddhsyood/+y+.`/./sssyyyyyyyyyyyyyyyyyyy///////+mmmMMMM"))
logo.append(list("MMMmmmo/////////+shddhhsoysohhy-ysssssssso++hyyyyyyyyyyy//////dmmNMMMM"))
logo.append(list("MMMNmmd+////////////oydhhhhhys//////////////+hyyyyyyyyyyy+///ymmmMMMMM"))
logo.append(list("MMMMNmmd++ooooo++ooo+//ohdyo+/////////////////yyyyyyyyhhhds+ymmmMMMMMM"))
logo.append(list("MMMMMNmmmmmmmmmmmmmmmdymmmmmmdo////////////////+yyyhmmmmmmmmmmmMMMMMMM"))
logo.append(list("MMMMMMNmmmyooodmmyohmmmmmyohmmd++osso+//////+ossshhmmmhooodmmmNNNNMMMM"))
logo.append(list("MMMMNmmmmmhy//hmm+/smmmmmo/smmmmmmmmmmmhs+ymmmmmmmmmmmdy+/hmmmmmmmmmMM"))
logo.append(list("MMNmmmhyoooo//hmm+/smmmmmo/smmmhssoosymmmmmmhsoooosydmmm+/hmmmyosmmmNM"))
logo.append(list("MNmmmo/+yhhy//hmm+/+sssss+/smmmssyhyo/ommmmo/+yhhh//dmmm+/hmh+/sdmmmMM"))
logo.append(list("Mmmmy/+mmmmm//hmm+/oyyyyy+/smmmdyysss//mmmy/+mmmmmhymmmm+/oo/sdmmmNMMM"))
logo.append(list("Mmmms/+mmmmm//hmm+/smmmmmo/smmy//ssyo/+mmmy/+mmmmmmmmmmm+/so/+hmmmmNMM"))
logo.append(list("MNmmd//shdho//shm+/smmmmmo/smmo/ohhy+//hdmm+/+yhdhyoymmm+/hmho/oyhmmmM"))
logo.append(list("MMmmmdso++osyoosmsohmmmmmsohmmdyo+oshooodmmmhso+++oydmmmsohmmmhoosmmmM"))
logo.append(list("MMMNmmmmmmmmmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNM"))
logo.append(list("MMMMMMNNNNNNNNNNNNNNNMMMNNNNNMMNNNNNNNNNNNMMNNNNNNNNMMMNNNNMMMNNNNNMMM"))
